### ISSUE TITLE
number of pages unreadable with Mint-Y-Darker theme

### ISSUE THREAD

**Issue by NikoKrause** [linuxmint/xreader#10]
Hey,

i use Linux Mint 18 Cinnamon with Mint-Y-Darker Theme.

I opened a PDF-file with the xreader, which has more than one page. But I don't know how many pages, because I can't read it at all (see image below)
![bildschirmfoto vom 2016-06-14 15-09-14](https://cloud.githubusercontent.com/assets/8415124/16044028/05cb9f82-3243-11e6-8f07-f48076b92188.png)

Also from the colors of the fonts used here, I would expect the button `Vorherige` to be active.
And the buttons `Nächste` and `Auf Seitenbreite einpassen` to be inactive.
But it is the other way around.

**Comment by JosephMcc** [comment]
This is actually an issue with the theme and should now be fixed in the master branch of Mint-Y.
