### ISSUE TITLE
Feature request: Back button

### ISSUE THREAD

**Issue by ecorm** [linuxmint/xreader#100]
For large hyperlinked documents, it's essential to have a "Back" button that allows you to navigate back after clinking on a link.

**Comment by Piiit** [comment]
@ecorm Hi, a back-button already exists. You can enable it through Menu>Edit>Toolbar

**Comment by uocxp** [comment]
is there any keyboard-shortcut for the back-button like "alt+ <-"? and is it possible to edit keyboard-shortcuts ?

**Comment by Piiit** [comment]
@uocxp Currently there is no such shortcut, nor any shortcut editor... 

@ecorm The new toolbar contains a new back/forward button similar to those in a browser. With right-click on them you can even see a list of your last positions within a document. I think, this issue can therefore be closed.

**Comment by JosephMcc** [comment]
Yeah, we went a slightly different route here but the functionality you had with the old back button is now part of the default toolbar.
