### ISSUE TITLE
Xreader searches for word that is continuation of non-existent word

### ISSUE THREAD

**Issue by ThorodanBrom** [linuxmint/xreader#135]
When search (Ctrl+F) done for a word, say 'Loll', and say it doesn't exist in the PDF, then 'Lolly' is searched, a new search is performed. It is noticed by using top/htop, the CPU usage spikes for searching 'Lolly', when it is not necessary. 
Issue currently produced on ver 1.2.2, on LMint Serena

**Comment by Piiit** [comment]
@JosephMcc I can reproduce this bug.
