### ISSUE TITLE
Please add again the toolbar buttons

### ISSUE THREAD

**Issue by geplus** [linuxmint/xreader#136]
Hi,
on the previous versions of xreader, you could customize the toolbar, adding and moving some buttons (like zoom buttons, print button etc.) where you want in the toolbar, as the older (good gui) versions of evince 
In version 1.4.1, you removed this function.

Please, bring back the customizable toolbar, because in my opinion it made the reader more usable.

Users that dislike buttons in their toolbar can simply remove or add them as they want.

**Comment by JosephMcc** [comment]
The old toolbar customizations are gone and aren't coming back.

**Comment by Piiit** [comment]
@geplus What buttons do you miss? You could make a "feature request" if you want to see a certain button... maybe it gets added. Although, the configurable toolbar is history to make the app look cleaner. NB: All functions are still accessible from the menu, we do not remove them.

**Comment by geplus** [comment]
@Piiit I simply like the freedom of customize the toolbar with the buttons I want in the programs I use, just a personal taste.

**Comment by acn128** [comment]
After upgrading to Mint 18.2 I also found that the toolbars in xreader aren't customizable anymore.
Now Mint also became a new GNOME where the programmers decide what is good for the user and what not.

Please bring back the old options!
