### ISSUE TITLE
Sometimes thumbnails in side pane don't show up

### ISSUE THREAD

**Issue by lqmanh** [linuxmint/xreader#139]
As the title says, thumbnails won't work correctly. If I scroll the side pane up or down, thumbnails could appear and disappear randomly.

I am using Xreader 3.4.1 + Cinnamon 3.4.1.

**Comment by Piiit** [comment]
@JosephMcc reproduced

**Comment by icarter09** [comment]
@lqmanh are you still experiencing this issue?

**Comment by lqmanh** [comment]
Hi @icarter09,

Unfortunately, I don't use Cinnamon anymore.

**Comment by icarter09** [comment]
@lqmanh no worries and thanks for the update.
