### ISSUE TITLE
Selecting option/radio buttons does not work correctly

### ISSUE THREAD

**Issue by graue70** [linuxmint/xreader#145]
# Steps to reproduce

1. Create an odt document with Libre Writer.
1. Add option/radio buttons and give all of them the same name.
1. Export the document to pdf, enabling form elements. This [Test.pdf](https://github.com/linuxmint/xreader/files/1091207/Test.pdf) was created just like that.
1. Open the pdf in xreader.
1. Click on one of the option buttons.
1. Click on another one of the option buttons.

# Expected behavior

Once the second option button is clicked, the previously selected option button should automatically be deselected.

# Actual behavior

After selecting the second option button, both the previously selected and the newly selected button are now selected. It is impossible to deselect a once selected button.

# Additional info

When I open the same pdf file with Foxit Reader, it works as expected.

Linux Mint 18.1 Cinnamon 64 bit
xreader 1.2.2
LibreOffice 5.1.6.2

**Comment by JosephMcc** [comment]
Reproduced in 1.4.

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
Xreader v2.2.3

Was able to reproduce the issue.

**Comment by icarter09** [comment]
Xreader 2.6.4
Mint 20 64bit

I'm no longer able to reproduce this issue with the provided test pdf. Believe this issue has been addressed.

**Comment by fg-ok** [comment]
Reproducable in Xreader version 3.2.2
Mint 20.3
