### ISSUE TITLE
Feature request: hide/show menubar

### ISSUE THREAD

**Issue by barabadzhi** [linuxmint/xreader#146]
Hi, guys! :wave: 

It's been a nice reader app :lollipop:, but will be even better
if you will consider adding hide/show menubar feature pressing `Alt` key,
same as Firefox browser does.

Seems pretty straightforward to implement. :100: 

Thanks! :smiley:

**Comment by astier** [comment]
Yes, would be a great feature.

**Comment by dqgls** [comment]
Nemo implements this as well and I really miss this option in some other Mint programs, especially xreader and xed. I don't have a large screen and I rarely use the menu bar so I'd really appreciate this feature being implemented in Mint's x-apps.

**Comment by memeplex** [comment]
This is desirable for a reader, you spend most of your time reading not interacting very much with the app. Space and focus is arguably more important here than in nemo, which supports hiding the menu bar.

In fact, it would be nice if the ability to hide/show the menu bar in a standard fashion were shared by the entire xapps suite.

**Comment by icarter09** [comment]
Xreader provides a "Presentation" view, which hides both the toolbar and the menu bar. But it is mapped to `F5` rather than `Alt`. Is that the same functionality as this feature request?

**Comment by MatthiasEder** [comment]
> Xreader provides a "Presentation" view, which hides both the toolbar and the menu bar. But it is mapped to `F5` rather than `Alt`. Is that the same functionality as this feature request?

not really as `F5` ("Presentation Mode") displays the PDF in full screen and you are not able have another application open split screen (for example text editor).

**Comment by astier** [comment]
> Xreader provides a "Presentation" view, which hides both the toolbar and the menu bar. But it is mapped to `F5` rather than `Alt`. Is that the same functionality as this feature request?

- Its fullscreen
- It hides the toolbar

**Comment by barabadzhi** [comment]
> > Xreader provides a "Presentation" view, which hides both the toolbar and the menu bar. But it is mapped to `F5` rather than `Alt`. Is that the same functionality as this feature request?
> 
> not really as `F5` ("Presentation Mode") displays the PDF in full screen and you are not able have another application open split screen (for example text editor).

I'll agree with this one.
There should be a way to get maximum space for the doc itself,
hiding all/most of the UI without going full screen. The key binding is an example, not a hard requirement.

**Comment by okaestne** [comment]
I opened a pull request which implements this feature. Can you please help to test it?
