### ISSUE TITLE
Certain fonts print with a box around them. Pdf font area being printed incorrectly

### ISSUE THREAD

**Issue by calexil** [linuxmint/xreader#147]
Certain fonts print with a box around them. Pdf font areas not being printed correctly
![pdf issue](https://user-images.githubusercontent.com/3487071/27751220-400ec98e-5da9-11e7-84ed-4085da06363d.png)

**Comment by JosephMcc** [comment]
What fonts? Do you have an example file that shows the problem?

**Comment by calexil** [comment]
Ill fix this in a bit.. it's way vague ... sorry

**Comment by calexil** [comment]
@JosephMcc here's an example file

[example.pdf](https://github.com/linuxmint/xreader/files/1129455/example.pdf)

**Comment by calexil** [comment]
closing because printing from adobe reader(legacy) works fine
