### ISSUE TITLE
Add a menu to customize the tool bar

### ISSUE THREAD

**Issue by KevinNadaud** [linuxmint/xreader#148]
I'm quite surprised when I made the update from LM18.1 to LM18.2, new icons are nice but there are no way to customize the tool bar.

Is it possible to re add a menu or something else to allow the customization of the tool bar (like in the previous version or in old version of evince) ?

Cheers

**Comment by mpetroff** [comment]
See #136 (and #96). Unfortunately, the developers don't seem to have any intention of restoring such functionality.

**Comment by KevinNadaud** [comment]
Ah ok, this is quite sad. I miss the shortcut to print and the one to show in presentation mode (F5)

**Comment by Piiit** [comment]
@mpetroff @KevinNadaud I think we could add something simpler. We are thinking about some generic toolbar editor for all xapps. Simpler means: No moving buttons, just hide/show them on a fixed position. This makes theming and maintenance a lot easier... What do you think?

**Comment by mpetroff** [comment]
That seems reasonable to me.

**Comment by KevinNadaud** [comment]
Yep, this is ok for me.

**Comment by oliver-joos** [comment]
+1 for "No moving buttons, just hide/show them"

I really miss a toolbar button to open the findbar! Several novice users asked me why they cannot search PDFs anymore with Mint 18.2. It was not easy to explain why it is now hidden in menu "Edit".
And I miss to choose the zoom level, like others already said in issue #149.

**Comment by LiteraryConnections** [comment]
Just lack to add my support for more toolbar items - quick links to displaying two pages, etc. I was taken aback when these vanished on upgrading from Mint 18.1 to 18.2

**Comment by whiskytroll** [comment]
I agree, it is unproductive to hide away often used functionality, and it is cluttered (=ugly AND unproductive) to leave seldom used functionality in full view. And since which functionality is often or seldom used it should certainly be a user choice. It's position isn't as important - if it is quickly accessible one will learn were it is with time. Perhaps it's even for the best: if it will make for consistency over the x-apps, it might make it easier to learn. I'd like to add also the possibility to remove any of the default items in the toolbar, they aren't all usable to me.

**Comment by Piiit** [comment]
Hi all,
I started to implement basic functionality to toggle toolbar buttons. It is just the first step towards a configurable toolbar though... See #178.

**Comment by Piiit** [comment]
@whiskytroll @LiteraryConnections @mpetroff @KevinNadaud @oliver-joos 
The first version of a simpler editable toolbar is ready, anyone here that wants to test/review it? Currently only history buttons and expand-window button are configurable, but it is a start... 

(btw. you need xapp now to build xreader)

**Comment by KevinNadaud** [comment]
Sorry I forget to answer. I would like to try the toolbar but I don't know exactly how to build xreader. Do you have some instructions or advises ? I have only Mint 18.3 on work computer so I don't want to do mistake.

**Comment by Piiit** [comment]
@KevinNadaud 
Hi, 
thanks for testing. You could start with the README also seen on the main page of this github repo. It is a bit outdated and needs some more information, which I want to provide when I have some time. 

One thing before you start with xreader is that you need to build xapps first.
It is now easy to install all the package you need to compile xapps and xreader, just type:
```
apt build-dep xapps xreader
```
Then follow the instructions of the readme. 

NB: If you don't want to overwrite your existing xreader installation, never execute `make install`, but run your compiled version of xreader from `./shell/xreader`. You probably need to install the new schemas thou...

Happy hacking!

**Comment by Piiit** [comment]
Hi all. Some items are customizable now, others will be added over time. Some are already listed in other issues, so this one can be closed in favour of more specific requests. 

Thx for all your feedback.
