### ISSUE TITLE
Missing zoom level select

### ISSUE THREAD

**Issue by mpetroff** [linuxmint/xreader#149]
```
 * Xreader 1.4.4
 * Distribution - Mint 18.2
```

Upon upgrading to Mint 18.2, the zoom level selector has gone missing&mdash;there is no longer any way to select a specific zoom level on the toolbar (nor in the menus).

![screenshot](https://user-images.githubusercontent.com/1450212/28097612-29ebaa30-667f-11e7-833e-5f52f1c53d63.png)

I'd really appreciate it if the zoom level dropdown was restored (minus the fit page type options, which have been moved elsewhere). I'd write a pull request to add it back, but I'm afraid I'll just be wasting my time, as the comments on #96 and #136 suggest that aesthetics are being favored over functionality.

**Comment by Piiit** [comment]
@mpetroff What do you think about adding it to the zoom buttons, as a right-click context menu?

**Comment by mpetroff** [comment]
That strikes me as an odd user interface design choice, since the only example I can think of where there is a right-click context on a button is the back and forward buttons in Firefox / Chrome. Regardless, while a context menu is better than nothing, I definitely prefer a dropdown, since it allows one to see the current zoom level with a glance, which I find helpful for printable documents such as PDFs.

**Comment by sdogg81** [comment]
@mpetroff Not to know the current zoom level is quite a mess... I would live with not having a dropdown menu as before and handling zoom levels by klicking the buttons, but at least the current level should be displayed somewhere. There's so much space on the left hand side of the zoom buttons... why not placing it there!?

**Comment by MysticLord** [comment]
Can verify that lack of current zoom and to a lesser degree customizable zoom percentage is annoying.  Reverted to viewing PDFs in Firefox.

**Comment by colintedford** [comment]
+1. I really need to pick (or write in) percentages (though it's nice), but I want to be able to see the doc at 100% and know if it's not.

**Comment by whiskytroll** [comment]
+1. A dropdown menu is a bare minimum, and ability to write a custom percentage would be a neat plus. If it's too ugly for the developers please at least add the possibility in some settings. It might also be hidden behind a triangle pointing down just beside the current zoom buttons, with the actual "current zoom level box" appearing when triangle is pressed - if that would make it prettier in some eyes.

**Comment by clefebvre** [comment]
Hi everybody,

First of all, thanks for your feedback and for the PR @mpetroff. I'll merge it now for the next release as I can see here that visually seeing the zoom level (or at least the fact that it's zoomed in) is something people want.

I don't think it's the right solution though and it duplicates the zoom buttons to a certain extent. Long term I think we could do better by doing similar than what's done in Firefox, i.e. a label which indicates the zoom level and which you can click to reset. We'd be left with two buttons (zoom-in/zoom-out) and we'd replace the zoom-reset button with that clickable label.

![image](https://user-images.githubusercontent.com/1138515/59363104-8a4eac80-8d2c-11e9-91e6-ec6310739bbd.png)

**Comment by Piiit** [comment]
Fixed in master
