### ISSUE TITLE
Case sensitivity button in Find does not make the search case sensitive

### ISSUE THREAD

**Issue by jaspergrond** [linuxmint/xreader#156]
```
 * Xreader version (xreader --version)
MATE Document Viewer 1.0.8
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Linux Mint 18 Sarah - Cinnamon 64-bit
```

**Issue**
Case sensitivity button in Find does not make the search case sensitive

**Steps to reproduce**
Ctrl+F
Click on Case Sensitive Button
Search for string that has a upper case variant in the same document

**Expected behaviour**
In the case sensitive search only exact matches to the string should be found

**Other information**
See attached screenshot  for example
![cs_off](https://user-images.githubusercontent.com/7441245/29086381-60a8128a-7c40-11e7-9033-59c1945a33a9.png)
![cs_on](https://user-images.githubusercontent.com/7441245/29086382-60aa0338-7c40-11e7-8786-ca9f31e330c6.png)

**Comment by NikoKrause** [comment]
I have tested it with several pdf files. Does it happen for you with every PDF file or only a certain one?

**Comment by jaspergrond** [comment]
I just tried the three other PDFs I had open and got the same result as the initial one.

**Comment by NikoKrause** [comment]
Do you have a free (not private) pdf to test with?

**Comment by jaspergrond** [comment]
These are the three pdfs I just mentioned.

[KruipIcke_SimpleX2_2010.pdf](https://github.com/linuxmint/xreader/files/1215825/KruipIcke_SimpleX2_2010.pdf)
[PawlikSchaye_Traphic_2008.pdf](https://github.com/linuxmint/xreader/files/1215824/PawlikSchaye_Traphic_2008.pdf)
[WiseAbel_MORAY_2011.pdf](https://github.com/linuxmint/xreader/files/1215826/WiseAbel_MORAY_2011.pdf)

**Comment by NikoKrause** [comment]
They work here. 
Sorry, I just saw, that you are using an older version. This issue has been fixed in a newer version than you use with this commit https://github.com/linuxmint/xreader/pull/73

**Comment by jaspergrond** [comment]
Ah sorry, my bad for not searching for it.

**Comment by NikoKrause** [comment]
Don't forget to close issue
