### ISSUE TITLE
page moving by hand tool

### ISSUE THREAD

**Issue by pinkpen** [linuxmint/xreader#161]
```
 * Xreader version 1.4.4
 * Distribution - Mint 18.2 Sonya, Cinnamon 64 bit
```
**Issue**
Feature Request

If the pdf page size is large or the font is very small and my monitors is small I have to use big zoom to see a piece of the page only. 
In that case I need the hand tool to move the page (up/down/right/left) to get the right part.
What I mean is the hand tool like adobe reader it has.

**Comment by Piiit** [comment]
Have you tried to use the middle mouse button for that?
