### ISSUE TITLE
Add annotations 

### ISSUE THREAD

**Issue by exdeus** [linuxmint/xreader#163]
* Xreader version : 1.44
 * Distribution - Mint 18.2

This is not a bug report but a features suggestion 

Evince, in it's last version 3.18.2 allows to [Add annotations
](url=https://help.gnome.org/users/evince/stable/annotations.html.en) to any pdf file 

As Evince and xreader seems very similar (Is xreader a fork ?) maybe would it be easy to implement this very usefull fonction ? 

**ERRATA** : Acutally xreader does support annotations ! the fonction is just not as easy to find :) My  bad ! 
(Cf screenshot) 

![capture du 2017-08-30 21-24-07](https://user-images.githubusercontent.com/329464/29890944-b29eb568-8dc9-11e7-87db-f35598a2eb2a.png)

**Comment by LiteraryConnections** [comment]
I have version 1.4.4, also on distribution Mint 18.2 and cannot find the annotations tool, let alone the toolbar icon shown in this screenshot. I would love to have this option, as I have to annotate some PDFs and the only way I can currently do this seems to be in Adobe's reader on Windows (or possibly Okular).

See [#141](https://github.com/linuxmint/xreader/issues/141) for reasons (and comments on) why it's not currently possible to add items to the toolbar.

**Comment by exdeus** [comment]
Sorry, I didn't make myself clear enough : The screenshot is from evince and not xreader. That's why you can't find the icon 

You can find the annotation option in xreader in the upper part of the side pannel (F9)

**Comment by exdeus** [comment]
You probably meant #148 ? 
That settles it. Thanks for your answer

**Comment by LiteraryConnections** [comment]
Sorry, yes, you are right, is _was_ #148.

I can see the option to _**view**_ annotations in the sidebar - but no tool or menu option to _**add**_ them to the document. Have I missed something?

**Comment by exdeus** [comment]
Yes you did ! Just look for the "+" button in the bottom left side of the side pannel :wink:

**Comment by LiteraryConnections** [comment]
Ah! You are right - but it's hard to find, as it only appears _**if**_ I open the side pane **_and_** choose to view annotations. This isn't at all intuitive - it doesn't appear in the _Edit_ menu, where I would expect it, or in any other menu - or in the documentation.

**Comment by Laurencio** [comment]
Yeah. But what about highligting? Is it hide round there? I could only manage to add text annotation.
And how can your remove an annotation?

**Comment by Piiit** [comment]
@Laurencio highlight and delete annotations are supported now... For any new or similar suggestion to improve xreader please file a new issue. Thx for your feedback 👍

**Comment by jondo** [comment]
I just want to remark that graphical annotations seem to be already covered by #66.

**Comment by ggrrll** [comment]
> Yeah. But what about "highligting" annotation? Is it hidden around there? I could only manage to add text annotation.
> And how can your remove an annotation?

you have to right click on the annotation, on the document > delete annotation

...but I agree that they should make it more user friendly... like adding items to the toolbar indeed...
