### ISSUE TITLE
Form fields out of place

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xreader#17]
Form fields are not shown correctly, that is, they are too small and do not match the underlying field size.
See screenshots:

1) Dropdown menue of combo boxes are too small, maybe they use the default size...
![auswahl_021](https://cloud.githubusercontent.com/assets/6096063/16293259/c1c19a6c-3918-11e6-919d-291884d7f8a7.jpg)

2) Text fields are too small and inner typed text is not shown correctly (moved to the bottom), I can see only the top of each letter:
![auswahl_022](https://cloud.githubusercontent.com/assets/6096063/16293266/cdf68612-3918-11e6-8e6b-d3e0ec5abe66.jpg)

3) Clicking an empty text field just shows the cursor, but not the background of a text field. When I type the first letter the background appears, but is out of place (like in 2).
![auswahl_023](https://cloud.githubusercontent.com/assets/6096063/16293269/d453a77e-3918-11e6-9303-9894247da423.jpg)

Please note that...
- ...this does not happen in the original version of mint cinnamon 17.3 of Atril.
- ...I tested this with the file from #12.
- ...the form fields are correctly sized and positioned, if zooming is used after clicking on a form field

**Comment by Piiit** [comment]
This is the test file from #12: [Inscription_SFA_2016_1.pdf](https://github.com/linuxmint/xreader/files/333467/Inscription_SFA_2016_1.pdf)

**Comment by JosephMcc** [comment]
Using your test file I can't reproduce this problem on Mint18 with the latest Cinnamon and xreader.

**Comment by Piiit** [comment]
@JosephMcc OK, but could you check it on Cinnamon 2.8.8 Mint 17.3 too?

**Comment by JosephMcc** [comment]
Sorry, I don't have it installed at the moment. I can check with someone in IRC when I get the chance.

**Comment by Piiit** [comment]
Found out that when I open a form field and then scroll down until it is outside of the window, and then scroll back, it gets resized correctly...

**Comment by xndrme** [comment]
I can confirm this bas behavior in Linux Mint 18 with xreader 1.0.8. 
I've noticed that the field is displayed first in a "standard" size and after some change (sometimes scrolling down, but also after a second attempt to fill the field) they are displayed in the expected size.
