### ISSUE TITLE
Trouble With Large Files

### ISSUE THREAD

**Issue by caltrop-3** [linuxmint/xreader#172]
```
 * Xreader version (1.4.4)
 * Distribution - (Mint 18.2)
```

**Issue**
scroll bar not working with large files
eg: GNU C Library Reference.pdf, 3.9 MB

**Steps to reproduce**
view large files

**Expected behaviour**
scroll bar behaving as it should with smaller files

**Other information**
 CPU: AMD Athlon(tm) II P360 Dual-Core x 2
 MEM: 3783MB (1009MB used)
SCSI: ATA WDC WD3200BEVT-7 320 GB
      TSSTcorp DVD+-RW TS-L633C
DISP: Resolution 1366x768 pixels
      OpenGL Renderer Gallium 0.4
      AMD RS880 (DRM 2.49.0 / 4.10.0-32-generic,LLVM 4.0.0)
 USR: caltrop (Elizabeth Thompson)
Linux Mint 18.2 Sonya
Kernal Linux 4.10.0-33-generic x86_64
MATE 1.18.0

**Comment by icarter09** [comment]
@caltrop-3 are you still experiencing this issue?

**Comment by caltrop-3** [comment]
system died💀currently computerlessnext system will be Arch or Manjaro, tired of Mintfeel free to unsubscribe me, my usernames & passwords died with the system ⚰️🥀🎃🦃🎄Liz 😼On Dec 17, 2019 23:02, Isaac Carter <notifications@github.com> wrote:@caltrop-3 are you still experiencing this issue?

**Comment by icarter09** [comment]
@caltrop-3 thanks for the update. Sorry to hear that. I'll close this ticket.
