### ISSUE TITLE
Zoom settings reset when selecting page from side pane

### ISSUE THREAD

**Issue by zhum** [linuxmint/xreader#175]
```
 * 1.4.4
 * Mint 18.2 x86-64
```

**Issue**

Zoom settings reset when selecting page from side pane.

**Steps to reproduce**

Open attached document. Select "View/Side pane". Select "View/Page width fit" (view is changed). Select any page from side pane - you'll jump to this page, but zoom settings will be reset to defaults.

**Expected behaviour**

Selected zoom preferences should be kept after jump to another page.
[Celerra_XML_API_v2_Programmer's_Reference.pdf](https://github.com/linuxmint/xreader/files/1358976/Celerra_XML_API_v2_Programmer.s_Reference.pdf)

**Comment by Piiit** [comment]
@zhum Hi, I tried this and could reproduce your issue when using "Content" view within the side pane. "Thumbnails" seem to work normally. Is that the same on your side?

**Comment by jay-wilkinson** [comment]
> @zhum Hi, I tried this and could reproduce your issue when using "Content" view within the side pane. "Thumbnails" seem to work normally. Is that the same on your side?

I can verify, Thumbnails work properly. Index view does not.

**Comment by icarter09** [comment]
Xreader 2.6.4
Mint 20 64bit

I'm unable to duplicate this issue. Both "Thumbnails" and "Index" are not resetting the zoom settings.

**Comment by jay-wilkinson** [comment]
Xreader 2.6.4
Mint 20 64bit

Index view is also working properly now for me as of 2.6.4. This can most likely be marked fixed and closed. Also THANK YOU to the coders that fixed this! I tend to read ebooks in Xreader and this really helps!

**Comment by alextpedro** [comment]
This bug seems to back on Xreader 3.8.2. Not with the thumbnails side-pane view, but the Index view. Selecting a page to jump to forces full screen width, regardless of chosen settings.

**Comment by ahogen** [comment]
I have `3.2.3+una` and I see this when viewing schematic PDFs generated from Altium. Every time I click on a title in the "Index" sidebar, xreader zooms out so nearly all pages are shown. I have to click zoom-in or one of the view buttons (e.g. "Reader View") to zoom back in to the page I selected.
