### ISSUE TITLE
Paragraph border not displayed

### ISSUE THREAD

**Issue by lukaszkruk** [linuxmint/xreader#176]
```
 * Xreader version - MATE Document Viewer 1.0.8
 * Distribution - Mint 18 Cinnamon
```

**Issue**
When viewing a document the right paragraph border is not displayed.

**Steps to reproduce**
Open [test.pdf](https://github.com/linuxmint/xreader/files/1374813/test.pdf) in xreader - note that there is not a vertical dotted line to the right of '2016'. 
Open the pdf in Chromium - note the line is displayed. 
Open the pdf in FIrefox - note the line is not displayed. 
Open the [ODT file](https://github.com/linuxmint/xreader/files/1374838/test.odt.zip) in Writer and see that the paragraph border is defined by the paragraph style.
 
**Expected behaviour**
Xreader should display the line the same way Chromium does.

**Comment by Piiit** [comment]
Tested it with okular, evince and atril. Everywhere the same problem. Adobe Reader, foxit and firefox show it correctly. Seems to be a poppler issue... Please report it there.

**Comment by lukaszkruk** [comment]
Thank you for checking, will take it up there!
