### ISSUE TITLE
No document scrolling

### ISSUE THREAD

**Issue by patricktokeeffe** [linuxmint/xreader#177]
```
 * Xreader version: 1.2.2
 * Distribution: Mint 18.1 Cinnamon 64-bit
```

I observe xreader "freezing" w.r.t. the document view. 

Immediately after opening a small (<1MB) file, the file is displayed but cannot be scrolled. Mousewheel, up/down keys, clicking thumbnails... none of these produce a change in the document view. Oddly, the right-hand scroll bar does not even render and cannot be used.

**Comment by paulreally** [comment]
Same problem here with Xreader version 1.4.4 and Mint 18.1 Cinnamon 64-bit.  I open with no thumbnail sidebar by default.  If I go to the view menu I can select to view the sidebar but it doesn't come up.  Close the document and re-open and the sidebar is there but I can't change pages.

**Comment by patricktokeeffe** [comment]
Closing since refs a stale version.
