### ISSUE TITLE
Scale/Fit to Print Options do not work

### ISSUE THREAD

**Issue by Falconus** [linuxmint/xreader#179]
```
 * Xreader version 1.4.4
 * Distribution - Mint 18.2 Sonya
```

**Issue**

When attempting to print a PDF page using Xreader, the page will not scale to fit. 

**Steps to reproduce**

1. Create a PDF document that has content outside of the printable area (for example, this document here: [diamond.pdf](https://github.com/linuxmint/xreader/files/1425445/diamond.pdf))
2. Attempt to print with the _Shrink to Printable Area_ or _Fit to Printable Area_ option selected

![printer_options](https://user-images.githubusercontent.com/9989529/32147651-2090c4be-bcc1-11e7-9b59-00c9c605228e.png)

**Expected behaviour**

All content will be printed without any information being lost to the margin areas. Content will be shrunk slightly if there is content in the PDF that would normally be outside of printable margins.

**Other information**

-Printer: Brother HL2240D
-Paper Size: Letter (8½ inches x 11 inches)
-Workaround: prints as expected using Okular

The document that printed looked like this (note that the corners of the diamond are missing):
![img_8132](https://user-images.githubusercontent.com/9989529/32147665-5295f4ca-bcc1-11e7-9973-45f362cbadae.JPG)

**Comment by icarter09** [comment]
@Falconus are you still experiencing this issue?
