### ISSUE TITLE
Back/Forward button in PDF with hyperlinks [Feature request]

### ISSUE THREAD

**Issue by zeehio** [linuxmint/xreader#180]
```
 * Xreader version (xreader --version) 1.2.2
 * Distribution - Mint 17.3
```

When I browse a PDF document with hyperlinks that link to other sections of the same document, I want to be able to browse back to where I was reading. This is explained [here](https://superuser.com/questions/22786/back-button-of-adobe-pdf-reader-after-clicking-a-hyperlink-whose-target-is-on-th).

It would be a great addition to xreader. Currently, if the PDF has a reference like [3] that links to the bibliography item at the end of the document, I have to remember the page number where I am, click the [3], see the reference, and write back the page number to continue reading. Being able to use `Alt + Left` to go back or something similar would make my life much easier.

Thanks for your great work!

**Comment by Piiit** [comment]
@zeehio 
Hi, 
we added history buttons now. So your request is partially fixed. Just some shortcuts missing, which will be added ASAP.

**Comment by emengd** [comment]
I don't think the behaviour of the back button is correct though. When you click a link, then click “back”, it takes you to the very first page and not to wherever you were when you clicked the link. At least this is what I observe on documents produced by LaTeX.

**Comment by orzechow** [comment]
@Piiit Please see the related #306 

Is there still a plan to add a shortcut support?

**Comment by orzechow** [comment]
> I don't think the behaviour of the back button is correct though. When you click a link, then click “back”, it takes you to the very first page and not to wherever you were when you clicked the link. At least this is what I observe on documents produced by LaTeX.

I can confirm this bug. It seems that sometimes links are followed without saving the current page into the history.

Best example is the [LaTeX hyperref manual](https://ftp.gwdg.de/pub/ctan/macros/latex/contrib/hyperref/doc/manual.pdf) itself :wink: 
1. Scroll down to page 2
2. Click any of the links
3. Click the "Go to previous history item" button

→ you end up on the top of page 1, not somewhere on page 2

I use xreader 2.2.3 on Linux Mint 19.2 Cinnamon.

**Comment by FrancoCalan** [comment]
+1 to this issue. I can confirm that the back button will return to whether the last link pressed was pointing, or to the beginning of the document, if no link was pressed beforehand (or to the page the program showed when de document was opened).

**Comment by icarter09** [comment]
I put up a PR for this ticket that hopefully addresses everything. I added keyboard shortcuts to the history buttons. They match up to what is in place for `Previous Page` and `Next Page`, which are in the `Go` menu as well. Also added a fix for how the `Previous History Item` was performing.

Let me know if this doesn't fix the issue or if the keyboard shortcuts need to be changed. Thanks.

**Comment by orzechow** [comment]
Thanks! Is there an easy way to test this without manual compilation?

**Comment by icarter09** [comment]
@orzechow you should be able to test now on the next xreader update.
