### ISSUE TITLE
Feature request: enable/disable saving of position within document

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/xreader#184]
```
 * Xreader version (xreader --version) 1.6.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
```

**Issue**

I open a PDF - which I will be using as a presentation - and skip through the slides to check them. I then close the document. When I re-open it - to use it as a presentation - I start on the final slide. This is a hindrance, and other PDF viewers allow one to change this behaviour.

**Comment by clefebvre** [comment]
Many thanks for contributing. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
