### ISSUE TITLE
Possible poor text rendering

### ISSUE THREAD

**Issue by ghost** [linuxmint/xreader#189]
```
 * Xreader version (xreader --version) 1.6.1
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
```

**Issue**

Text in a PDF looks much better in Adobe (run via Crossover) than Evince. Still, the problem *could be* with the PDF file.

**Steps to reproduce**

Open the same file (available via https://www.ascorbius.com/drewwagaroolite) in Evince and in Adobe.

**Expected behaviour**

The text should look as good in Evince as it does in Adobe.

**Other information**

Screenshot of a page in Evince:

![image](https://user-images.githubusercontent.com/9998846/33812122-71e9a502-de12-11e7-92dc-5cf3d1a67c6e.png)

Screenshot of the same page in Adobe:

![image](https://user-images.githubusercontent.com/9998846/33812125-81b1b8e4-de12-11e7-9626-2837a4f48534.png)

EDIT: The text looks better in Calibre than in Evince - as well.

**Comment by clefebvre** [comment]
Thanks, please provide the exact link to the PDF you're testing with.

**Comment by clefebvre** [comment]
It seems to be using Times New Roman... it looks fine here on my Xreader, but maybe it's because we've different fonts installed.

**Comment by clefebvre** [comment]
Ah yes, I've got MS fonts installed, so Times New Roman is available locally.

**Comment by clefebvre** [comment]
Looking at Calibre, it seems to be providing its own copies of the Liberation Fonts. Can you try the following?

- Close all xreader windows
- Install fonts-liberation
- Reopen the document in xreader

See if the font rendering works better.

Liberation's goal is to provide free alternatives to MS core fonts. If that solves the issue we can consider shipping these by default.

**Comment by CottonEaster** [comment]
`fonts-liberation` was installed when I took the screenshot. I still have `fonts-liberation` installed and the PDF (which is the document/link labelled 'Altera' on the page I gave above) looks the same now as it did in the screenshot above.

Should I provide you with further information about the font setup on my system?

**Comment by icarter09** [comment]
Closing issue due to original submitter no longer present on github.
