### ISSUE TITLE
Tool bar adjustment.

### ISSUE THREAD

**Issue by capsicumw** [linuxmint/xreader#193]
Xreader version 1.6.1
Binary package from Manjaro repos
Xfce4, kernel 4.4
I suppose this could be a feature request. Mainly I'm posting an "issue" because I couldn't find any general-discussion method of contact. 
I would like to reduce the height of the toolbar, essentially just eliminating the empty border and keeping icon size to gain a few pixels of viewing space on my little laptop screen. Is this configurable after compile time or hard coded? If hard coded which file should I play with, I looked around here for a few minutes but did not find the section.

**Comment by JosephMcc** [comment]
It should mostly be down to your theme. Most themes add padding to the buttons and the toolbars around them that create the space you're talking about.
