### ISSUE TITLE
Remove libnemo dependance

### ISSUE THREAD

**Issue by Magissia** [linuxmint/xreader#198]
```
 * Xreader version (xreader --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
```

**Issue**
Using caja as file manager, i'm forced to keep libnemo to use xreader because xreader depends on it, make it depend on my file manager libs or make it not depend on a file manager lib.

xreader should make use of the lib if available and deal without it if absent.

**Steps to reproduce**
Install Linux Mint Mate
Uninstall libnemo
Be greeted with a window telling you it will remove xreader too

**Expected behaviour**
Not requiring libnemo when not using cinnamon

**Other information**

**Comment by leigh123linux** [comment]
Fixed https://github.com/linuxmint/xreader/commit/4d06e8632a7583b72ecff010580f0011bd32421e
