### ISSUE TITLE
Properties access crashes the application

### ISSUE THREAD

**Issue by KDB2** [linuxmint/xreader#2]
Dear team,

On LMDE2, xreader 1.0.3 crashes when the property menu is accessed (File --> Properties) (segmentation fault).

KDB@KDB-laptop ~/Téléchargements $ xreader sicp.pdf
(xreader:9909): Gtk-WARNING **: Symbolic icon pan-down-symbolic-ltr of size 16 is in an icon theme directory of size 128
(xreader:9909): Gtk-WARNING **: Symbolic icon pan-down-symbolic-ltr of size 16 is in an icon theme directory of size 128
(xreader:9909): Gtk-WARNING **: Attempting to store changes into `/home/KDB/.local/share/recently-used.xbel', but failed: Le renommage du fichier « /home/KDB/.local/share/recently-used.xbel.2230GY » vers « /home/KDB/.local/share/recently-used.xbel » a échoué : échec de g_rename() : Périphérique ou ressource occupé
(xreader:9909): GLib-GObject-WARNING **: specified class size for type 'EvPropertiesView' is smaller than the parent type's 'GtkVBox' class size
(xreader:9909): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(xreader:9909): GLib-GObject-CRITICAL **: g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed

Erreur de segmentation

Same pdf shoes correct output with Evince 3.14.1

Regard,
KDB

**Comment by Jeroen0494** [comment]
I have the same problem. I have attached the coredump obtained via coredumpctl in the following manner:
`coredumpctl -o xreader.coredump dump /usr/bin/xreader`

[xreader.coredump.zip](https://github.com/linuxmint/xreader/files/252390/xreader.coredump.zip)
