### ISSUE TITLE
Xreader does not open "file open dialog" with directory set to recent file directory

### ISSUE THREAD

**Issue by jungornti** [linuxmint/xreader#20]
Hello!

When i'm open xreader and try to open a file, it does not show me recent opened file directory, but evince does.
There are no way to open recent files from xreader, so using it not as comfortable as evince.

**Comment by Piiit** [comment]
Hi @jungornti,
I think this is fixed now! Could you please check and close this issue or give some feedback.Thank you!

**Comment by jungornti** [comment]
Thank you very much, it is working! (Y)
