### ISSUE TITLE
Crash in cairo-scaled-font.c:459

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/xreader#201]
```
 * Xreader version: 1.6.2
 * Distribution: Mint 18.3 Cinnamon 64-bit
```

**Issue**
xreader age-of-empires-the-rise-of-rome_windows_0gg6-manual.pdf 
xreader: ../../../../src/cairo-scaled-font.c:459: _cairo_scaled_glyph_page_destroy: Assertion `!scaled_font->cache_frozen' failed.
Aborted

**Steps to reproduce**
This is the PDF:
https://www.myabandonware.com/download/gg6-age-of-empires-the-rise-of-rome

**Comment by mickaelalbertus** [comment]
It seems to be a cairo bug. Here are links of the reported bug and fix:
[https://bugs.freedesktop.org/show_bug.cgi?id=85141](https://bugs.freedesktop.org/show_bug.cgi?id=85141)
[https://cgit.freedesktop.org/cairo/commit/?id=5fd0b8710f125bb33c55d75fcc8252996b403e2d](https://cgit.freedesktop.org/cairo/commit/?id=5fd0b8710f125bb33c55d75fcc8252996b403e2d)

**Comment by icarter09** [comment]
@kneekoo did @mickaelalbertus comment help you fix the issue?

**Comment by kneekoo** [comment]
I just tested that PDF in **Xreader 2.2.3** under **Linux Mint 19.2** and it opened up normally, I could scroll, select and search text, but the image rendering isn't smooth, compared to the one done by Chromium. Should I report this as a different issue or is this fine?

**Chromium:**
![pdf-chrome](https://user-images.githubusercontent.com/566306/71055295-58902580-2155-11ea-9ebb-916f77254f04.jpg)

**Xreader:**
![pdf-xreader](https://user-images.githubusercontent.com/566306/71055296-5928bc00-2155-11ea-8d48-2cd0451a12ef.jpg)

**Comment by icarter09** [comment]
@kneekoo thanks for the update. I would create a new issue and close this one out. (if you feel the new issue isn't related to the original problem)

**Comment by kneekoo** [comment]
They're obviously unrelated, so I'll open a new issue. :)
