### ISSUE TITLE
Changing page not possible in the Page View after resizing

### ISSUE THREAD

**Issue by astier** [linuxmint/xreader#209]
```
 * Xreader version 1.6.2
 * Distribution - Mint 18.3
```

**Issue**

In the Page View it is not possible to change the page with the middle mouse button or with the arrow keys after resizing the document. However, it works if one goes in the Page View mode without resizing it afterwards. This would be useful because on a big screen I sometimes wish to make the document smaller while using the Page View but still be able to change the pages with the mouse.

**Steps to reproduce**

1. Open a document with at least two pages.
2. Change to the Page View mode.
3. Shrink the document.
4. Try to change the page by using the middle mouse button or arrow keys.

**Expected behaviour**

It should be possible to change the page with the middle button or arrow keys.

**Comment by mickaelalbertus** [comment]
I think it's a normal behavior because when you choose the Page View mode, it sets the sizing mode to best fit and when you resizing the document (you mean zoom in or zoom out, right?) it changes this mode. Tell me if I didn't understand? :)

**Comment by astier** [comment]
There are two modes. *Reader View* which is continuous and fits the page width. And then *Page View* which is non-continuous and fits best the page. I am using the Page View Mode often because its non-continuous not because of the best fit or is non-continuity not supposed to be a feature? :)

**Comment by mickaelalbertus** [comment]
Ok I think I understand what you mean. Suppose that you're in Page View mode and you zoom out, you want to go to next page or previous page with arrow keys? (the middle button doesn't work or maybe I don't know how to use it what is possible) But if you zoom in and use arrow keys, xreader scroll up or down (which is normal). The actual behavior is the same when you zoom out and you want to change it? Am I right?

**Comment by astier** [comment]
If I am in the Page View Mode and zoom out I would like to change the page by scrolling the middle mouse button. Arrow keys would also be nice but I also could use the Page Up/Down buttons because they always work. The thing is when I am in the Page View Mode and DON’T zoom out/in I can change the page with the middle mouse button or the arrow keys (and page down/up buttons of course). It only doesn’t work if I zoom in/out. And yes, if I zoom in then I can scroll with the arrow keys and the middle mouse button but still not change the page.
