### ISSUE TITLE
Will not print in landscape

### ISSUE THREAD

**Issue by Rob1911** [linuxmint/xreader#215]
Can not get Xreader to print in landscape. (should pickup automatically that document is in shown in Landscape)

Operating System:   Linux Mint 18.3 Cinnamom 32-bit
Cinnamon Version:   3.6.7
Linux Kernel:       4.10.0-38-generic
Processor:          Intel Core 2 CPU  6600 @ 2.40GHz x2
Memory:             7.9 GiB
Hard Drives:        2836.7 GB
Graphics Card:      NVIDIA Corporation GM107[GeForce GTX 750]

Printer:            HP Laserjet P2055d
Software drivers:   Cups  (as near as I can figure)
Xreader:            1.6.2

Have the printer set in Printer Properties, Job Options, Landscape 270 (have tried landscape 90).  Then in Print, Page Setup, Orientation Set it for landscape (have tried reverse landscape).

Document shows in Landscape but when a preview is done portrait is shown.

What ever steps are taken in always prints in portrait.

Thanks for the help.
Rob

**Comment by Piiit** [comment]
@Rob1911 Have you enabled "Auto Rotate and center" inside Print>Page Handling options of xreader? With that option it will rotate your documents back.

**Comment by Rob1911** [comment]
SOLVED:
Went from cups to HPLIP software.  It solved the problem.
In answer to the question was "Auto Rotate and center" enabled.  Response: Yes.
Thanks,
Rob
