### ISSUE TITLE
Shortcut to (un)hide the toolbar

### ISSUE THREAD

**Issue by astier** [linuxmint/xreader#216]
```
* Xreader version 1.6.2
* Distribution - Mint 18.3
```

**Issue**
It is only possible to (un)hide the toolbar by clicking trough the menubar. It would be nice to have a shortcut for this.  For example there is already a shortcut to (un)hide the side pane. Thanks.

**Comment by mickaelalbertus** [comment]
Maybe it should be a shortcut given by xapps library? So we will have a common action for every xapps.

**Comment by astier** [comment]
Didn't know xapps exists. Sound reasonable. Should I open an issue there?

**Comment by mtwebster** [comment]
This is the right place for this request, the toolbar (and any shortcuts) are handled here.

**Comment by gilbertohasnofb** [comment]
@mtwebster Does this mean that this feature needs to be requested in each individual repository of the X-apps?
