### ISSUE TITLE
xreader: malloc.c:2394: sysmalloc: Assertion for some PDFs

### ISSUE THREAD

**Issue by brupje** [linuxmint/xreader#219]
```
xreader 1.4.4
Distributor ID:	LinuxMint
Description:	Linux Mint 18.3 Sylvia
Release:	18.3
Codename:	sylvia

```

**Issue**
Program closes unexpectedly with malloc.c error.

xreader: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_
[test.pdf]
end & (pagesize - 1)) == 0)' failed.
[test.pdf](https://github.com/linuxmint/xreader/files/1867650/test.pdf)

**Steps to reproduce**
Open attached document

**Expected behaviour**
Show the document

**Other information**
Started happening recently, maybe after an update.

**Comment by Piiit** [comment]
@brupje Is it solved now?

**Comment by brupje** [comment]
1.8.5 with lint mint 19 works ok :)

**Comment by Piiit** [comment]
@brupje Thanks for your cooperation :-)
