### ISSUE TITLE
checkbox buttons do not work

### ISSUE THREAD

**Issue by 55TTKKSS** [linuxmint/xreader#220]
```
 * Xreader 1.4.4
 * Linux Mint 18.2 Sonya - Cinnamon 3.4.6 (Gtk 3.18.9-1ubuntu3.3)
```
**Issue**
Checkboxes do not work properly: when you click on them, they do not get the checked-character, the character (for "checked") does not appear into the checkbox, that remains empty.

**Steps to reproduce**
Open the pdf in xreader.
Click on one check-box.

**Expected behaviour**
A mark signaling "checked" should appear in the checkbox. 

**Other information**
The check-box was perfectly functional in adobe reader; so the pdf was properly built. 
Example: in the following pdf, if you click on the check-box located after the expression "Profesional con Interés Legítimo", it will remain empty.
https://sir-aut.cba.gov.ar/FormulariosPDF/DIR%20titulares.v2.pdf

**Comment by icarter09** [comment]
@55TTKKSS are you still experiencing this issue?

**Comment by 55TTKKSS** [comment]
yes; it has evolved, thow... There are some checkboxes that display a 
character, like a "4" or an "8" instead of the proper character (it 
being the "checked" symbol, something like a square root)..., and that 
seems to be some kind of character code error..., I think...

J.A.L.

**Comment by icarter09** [comment]
Thanks for the update. I noticed that same issue with the "4" character.

**Comment by 55TTKKSS** [comment]
Hey, one more thing...

The issue with the "4", that in some cases comes to be an "8" instead of 
a "4", has some particular implications:

If you work with the linux app, and save the document with the "4" 
and/or the "8", and/or whatever else could appear instead; and then you 
take that document to a Windows machine, and open the file with the 
Adobe acrobat reader, you will see that the correct characters appear 
instead of the "4", "8", and whatever else you could have got in linux...

That is why I suspect that is a "characters codding" problem; some think 
like this: the app has the correct codes for each character; but when 
the SO, or something else in between shows the characters, it somehow 
shows the characters from a different set of characters, in which the 
"4" is at the same "spot" where (has the same code that) in a different 
set of characters is located the "checked" character...

I do not know, really...

Thank you for for asking!

Good and happy and prosperous new year!

J.A.L.

**Comment by icarter09** [comment]
@55TTKKSS I believe this issue might be fixed now, but I'm unable to access the provided PDF to test it out. Can you see if this is still an issue and if so, could you provide a sample PDF? Thanks.

**Comment by 55TTKKSS** [comment]
Hey, icate09!
First the first: I am on Manjaro, now, because of some issues the kernels implemented in Linux Mint have with my Athlon 200ge; I am still using xreader, because it is awesome, but I don't know if what I am about to say is valid in Linux Mint today.
Second: I haven't had to use the check button feature during all these time, so I didn't know if it was or not already fixed...
I tried the feature today, and it worked (still, in Manjaro, I don't know if it would work in Mint...).
I am attaching a sample of the pdf that showed the problem. 
[Formulario G.v3 - unificado corregido.pdf](https://github.com/linuxmint/xreader/files/5367521/Formulario.G.v3.-.unificado.corregido.pdf)

Thanks for the hard work and for solving the issue!
J.A.L.

**Comment by icarter09** [comment]
@55TTKKSS thanks for the pdf. Looks like the checkboxes are working and showing a check mark. I'm going to close this issue. Thanks.
