### ISSUE TITLE
The pdf scrolls moving the mouse even from other monitors

### ISSUE THREAD

**Issue by riksoft** [linuxmint/xreader#225]
```
 * Xreader version Any
 * Distribution - Mint 18.3 or 17
```

**Issue**
With apparently no reason, xreader starts to scroll the document in sync with the up/down movement of the mouse, even if out of focus and even on another monitor.

**Steps to reproduce**
After many months of this problem I've finally found the cause and a way to reproduce the problem systematically.
1) Open a pdf.
2) With the mouse select PART of a word (not all the word).
3) Copy with CTRL+C
4) At this point, if you move the mouse up/down Xreader scroll automatically.

**Expected behaviour**
Not scrolling, especially when Xreader window is out of focus.

**Other information**

**Comment by nick-s-b** [comment]
I'm experiencing the same bug. You don't even have to copy anything to experience this... it will randomly scroll on its own. Even if the window is in the background, it will sometimes scroll on its own as you move the mouse around completely outside the Xreader's window.
