### ISSUE TITLE
xreader displays postscript pages upside down

### ISSUE THREAD

**Issue by jakesalomon** [linuxmint/xreader#226]
```
 * Xreader version (xreader --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**
I have been using a2ps for a very long time to format my source files. This produces postscript output. When I use xreader to view it I see the pages upside down, albeit in the correct landscape mode and in the correct order.  A minor gluteal pain to click on [Edit][Rotate] twice to view it right-side up.

Note that in  under **Windows/Cygwin**, I use a2ps as well and view it with GhostScript I have no such problem.  By the way, when I view it with gs (ghostscript viewer) in Linux Mint it displays the pages vertically, which is of little help for a landscape document.

**Steps to reproduce**
1. Run a2ps on any source file.  Use options: --columns=2 --landscape
    example:
    $ a2ps --columns=2 --landscape -o mysource.c.ps mysource.c
2. Run:
    $ xreader mysource.c.ps &

**Expected behaviour**
Display the landscape pages right-side up

**Other information**

**Comment by leigh123linux** [comment]
Works fine here.
Also you failed to provide basic info (see template).
