### ISSUE TITLE
quotation marks rendered incorrectly in document

### ISSUE THREAD

**Issue by mec3307** [linuxmint/xreader#228]
```
 * Xreader version (xreader --version)   xreader/sylvia,now 1.6.2+sylvia amd64 [installed]
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 18.3
```

**Issue** quotation marks rendered as i character with ` or ^ instead of dot on top.

**Steps to reproduce** open a document with quotation marks

**Expected behaviour** render quotation marks

**Other information** tested document with Adobe Reader v9, pdf2txt command, and mupdf the quotation marks rendered correctly.
![xreader display](https://user-images.githubusercontent.com/39223565/39960557-7f64e49e-55ea-11e8-85e9-ac3114c997ae.png)

**Comment by icarter09** [comment]
@mec3307 are you still experiencing this issue?

**Comment by mec3307** [comment]
@icarter09  - The issue does not appear with current software versions. 
xreader-common/tina,tina,now 2.2.3+tina all [installed]
cat /etc/issue
Linux Mint 19.2 Tina
