### ISSUE TITLE
Unimplemented annotation: POPPLER_ANNOT_STAMP

### ISSUE THREAD

**Issue by eku** [linuxmint/xreader#230]
```
 * Xreader version (xreader --version)
   xreader-1.8.1-1.fc28
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   Fedora 28
```

**Issue**

** (xreader:5318): WARNING **: 18:34:28.012: Unimplemented annotation: POPPLER_ANNOT_STAMP, please post a bug report on Xreader bug tracker (https://github.com/linuxmint/xreader/issues) with a testcase.

**Steps to reproduce**

xreader instruction_booklet.pdf

**Expected behaviour**

No warning at all.

**Other information**
Can't attach the PDF file.

**Comment by Piiit** [comment]
Duplicate of #66
