### ISSUE TITLE
SIGSEGV EvJobScheduler when opening PDF file 

### ISSUE THREAD

**Issue by eku** [linuxmint/xreader#231]
```
 * Xreader version (xreader --version)
    xreader-1.8.1-1.fc28
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   Fedora 28
```

**Issue**
SIGSEGV when opening a PDF/1.5 file.

**Steps to reproduce**
xreader pdf_file
I can't supply the file as the content is confidential.

**Expected behaviour**
Opens and displays the file.

**Other information**

Thread 10 "EvJobScheduler" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc129d700 (LWP 4805)]
0x00007fffc089425b in build_tree (pdf_document=pdf_document@entry=0x555555c2c700, model=model@entry=0x7fff70043d30, parent=parent@entry=0x0, iter=iter@entry=0x55555598ef00) at ev-poppler.cc:1212
1212			action->goto_dest.dest->change_zoom = 0;

(gdb) bt
#0  0x00007fffc089425b in build_tree (pdf_document=pdf_document@entry=0x555555c2c700, model=model@entry=0x7fff70043d30, parent=parent@entry=0x0, iter=iter@entry=0x55555598ef00) at ev-poppler.cc:1212
#1  0x00007fffc0896e9a in pdf_document_links_get_links_model (document_links=<optimized out>) at ev-poppler.cc:1261
#2  0x00007ffff754bdde in ev_job_links_run (job=0x555555d7f680) at ev-jobs.c:385
#3  0x00007ffff754dab2 in ev_job_thread (job=0x555555d7f680) at ev-job-scheduler.c:184
#4  ev_job_thread_proxy (data=<optimized out>) at ev-job-scheduler.c:217
#5  0x00007ffff549bf2a in ?? () from /lib64/libglib-2.0.so.0
#6  0x00007ffff4e7b594 in start_thread () from /lib64/libpthread.so.0
#7  0x00007ffff4baf00f in clone () from /lib64/libc.so.6

**Comment by icarter09** [comment]
@eku are you still experiencing this issue?

**Comment by eku** [comment]
@icarter09 did you fix it? In which version?

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
Xreader v2.2.3

I'm not able to reproduce this issue with any PDF. But you did state in the issue that you aren't able to supply the PDF in question. Just checking up with you to see if this issue was ever resolved.
