### ISSUE TITLE
Incorrect centering of the page when printing

### ISSUE THREAD

**Issue by AlexD67** [linuxmint/xreader#239]
```
 * Xreader version 1.8.5
 * Distribution - (Mint 19)
```

I noticed that when printing Xreader doesn't "center" the page right when "scale" is greater or lower than 100%. Instead, the page is moved off the center diagonally.

**Comment by Piiit** [comment]
@AlexD67 Could you please provide a step-by-step explanation how to reproduce your issue. What printing options have you set exactly? Do you have a screenshot eventually?

**Comment by Piiit** [comment]
@AlexD67 I managed to reproduce this issue now. It is important to not select "scale to printable area" and other autoscale options. I open a PR to fix this issue now

**Comment by AlexD67** [comment]
Hello! Sorry I didn't answer your message, I've been really busy these few
days. Thank you for your efforts to improve the program! May I also ask,
when I open  multi page PDF file, it takes a few seconds to open it (while
the cursor is spinning.) Is that normal? Other PDF readers don't seem to do
that. ( Even infamos Adobe reader 9!) :) . And I don't remember seeing it
before. Did it get slower with time! Anyway, just thought to mention it.
Thanks so much again for your wonderful work! I love Linux mint!

**Comment by Piiit** [comment]
@AlexD67 Thanks for your kind words. Please open a new issue describing the performance problems as detailed as possible. 

Cheers, 
Peter
