### ISSUE TITLE
Zoom by Control+scroll is too sensitive

### ISSUE THREAD

**Issue by TomaszGasior** [linuxmint/xreader#240]
* Xreader version : 1.8.5
 * Distribution: Arch

**Issue**
As in title.

**Steps to reproduce**
Just try to zoom document by Control+scroll and then compare it with Atril end Evince. Both Atril and Evince are zooming in proper speed. Xreader is too fast — it's hard to set expected zoom size.

**Comment by mickaelalbertus** [comment]
I totally agree and I will fix it as soon as possible. It's a "bug" from my part because I add the smooth scrolling so it's too sensitive for now.

**Comment by fugata** [comment]
I second this:  I'm using Xreader 2.0.2 on linux mint xfce 19.01, and ctrl+scrolling is not useable due to over-sensitivity.  If fixing this takes too much time for now, as a temporary solution is it possible to manually enter a zoom level (e.g. as in evince)?

Thanks for your consideration!

**Comment by icarter09** [comment]
@TomaszGasior @fugata are either of you still experiencing this issue? Thanks.
