### ISSUE TITLE
Warning when new window is opened

### ISSUE THREAD

**Issue by TomaszGasior** [linuxmint/xreader#243]
```
 * Xreader version: 1.8.5
 * Distribution: Arch
```

**Issue**
This warning is printed to console when you start Xreader without opening file and when there is no recently opened files:
```
(xreader:30634): Gtk-CRITICAL **: 23:15:51.342: gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
```

**Steps to reproduce**
Open new Xreader window without file, when there is no recently opened files. Warning is not shown immediately. You have to maximize and restore app window, click on empty area or resize it.

**Expected behaviour**

**Other information**

**Comment by Piiit** [comment]
Fixed in master
