### ISSUE TITLE
Integrating Xreader with very powerful PDF editor !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/xreader#244]
Hi. 

1st of all, I do not know if you have plan to add edit power for Xreader or not. You (Cinnamon team) bring very nice power for Linux by creating Cinnamon DE & making it stable for reasonable degree after it was unstable. You can add more power for Cinnamon (& for Linux in general) if you add editing power for Xreader. 

You know that PDF editing is currently a failure ! It is the poor area in Linux.

If you have a plan to make xreader of editing power for PDF file, then I would like to suggest on you to integrate a very powerful free & open source PDF editor with extensive options (though still need further development to add new features) called jPDF Tweak:

https://sourceforge.net/projects/jpdftweak/

the program is very powerful ! It need further development to be in the ideal level to be in near from Adobe acrobat pro of Windows .....

Unfortunately, the developer of jPDF Tweak stop from it's developing. No more new features will be added. The project is dead. The last message from him to me in replay to my last e-mail was as following:

> Hello Yousif,
> 
> Am 23.04.2018 um 13:32 schrieb Yousif J. Kadom:
> > Hi. I would like to ask if jPDFTweak is still alive or it's development
> > discontinued?
> 
> It is very low priority for me. In other words, critical bugs may still
> get fixed, but probably not many new features any more.
> 
> > It was very long time since last time jPDFTweak was updated ! It seem
> > that it is now out of development .......
> 
> That depends. Last release was 2011. I am using software that has not
> been updated since 2002... As long as it works, it should not hurt 
> 
> Regards,
> 
> Michael

Can you integrate (or add an integration option) of Xreader with jPDF Tweak ? It need with that to further develop jPDF Tweak & adding new features to it.

I'm not programmer & I do not know if such integration possible or not. Please examine it.

Best.

**Comment by Nokia808** [comment]
I forgot to add this link which explain the power of this dead project:

http://jpdftweak.sourceforge.net/

**Comment by Piiit** [comment]
@Nokia808 Xreader is written in c and this tool in Java. It would be very tiresome to make both fit. Xreader's purpose is more of a reader then a manipulation tool.

Thx for your suggestions, but this is too far off our road :-)

Cheers,
Peter
