### ISSUE TITLE
Hide the side panel when going full-screen

### ISSUE THREAD

**Issue by kneekoo** [linuxmint/xreader#252]
```
 * Xreader 1.6.1
 * Mint 18.3 64-bit Cinnamon
```

**Issue**
The side panel doesn't hide when viewing an image full-screen.

**Steps to reproduce**
1. Open an image with Xviewer
2. Enable the side pane via **View** -> **Side Pane** (Ctrl+F9)
3. Enter full screen via **View** -> **Fullscreen** (F11)

**Expected behaviour**
I don't know if anyone cares about the metadata while viewing images in full screen, but by default I consider this info unnecessary. It would be nice if it was hidden, and displayed again once the viewer goes back to the windowed mode.

**Comment by Piiit** [comment]
This is the wrong repository. Please feel free to reopen this issue on xviewer's repo instead.
