### ISSUE TITLE
Cannot open Scrum_Revealed_by_International_Scrum_Institute.pdf

### ISSUE THREAD

**Issue by kklavei** [linuxmint/xreader#254]
```
 * Xreader version 1.6.2
 * Distribution - Linux Mint 18.3 MATE 64-bit
```

**Issue**

Cannot open Scrum_Revealed_by_International_Scrum_Institute.pdf. Xreader closes immediately.

**Steps to reproduce**

Order Your Free Scrum Book from https://www.scrum-institute.org/index.php. Download it and try open it.

**Expected behaviour**

Open document for reading.

**Other information**

Kernel 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

kern.log:

Oct  4 21:54:10 localhost kernel: [46374.860348] EvJobScheduler[30705]: segfault at 50 ip 00007f836793f9a0 sp 00007f8374e48888 error 4 in liblcms2.so.2.0.6[7f836792b000+52000]

syslog:

Oct  4 21:54:10 localhost org.x.reader.Daemon[3247]: RegisterDocument registered owner ':1.253' for URI 'file:///home/USERNAME/Downloads/Scrum_Revealed_by_International_Scrum_Institute.pdf'
Oct  4 21:54:10 localhost org.x.reader.Daemon[3247]: Watch name':1.253' appeared with owner ':1.253'
Oct  4 21:54:10 localhost org.x.reader.Daemon[3247]: RegisterDocument process pending invocations for URI file:///home/USERNAME/Downloads/Scrum_Revealed_by_International_Scrum_Institute.pdf
Oct  4 21:54:10 localhost kernel: [46374.860348] EvJobScheduler[30705]: segfault at 50 ip 00007f836793f9a0 sp 00007f8374e48888 error 4 in liblcms2.so.2.0.6[7f836792b000+52000]
Oct  4 21:54:10 localhost org.x.reader.Daemon[3247]: Watch name':1.253' disappeared
Oct  4 21:54:10 localhost org.x.reader.Daemon[3247]: Watch found URI 'file:///home/USERNAME/Downloads/Scrum_Revealed_by_International_Scrum_Institute.pdf' for name; removing
Oct  4 21:54:40 localhost org.x.reader.Daemon[3247]: Timeout; exiting daemon.

**Comment by icarter09** [comment]
@kklavei are you still experiencing this issue?

**Comment by kklavei** [comment]
I'm not experiencing this issue anymore with

Xreader version 2.2.3
Linux Mint 19.2 MATE 64-bit
Kernel 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

If it's OK, I'll close the issue?

**Comment by icarter09** [comment]
@kklavei thanks for the update and yes to closing the ticket.

**Comment by kklavei** [comment]
Closed because not reproducible with Xreader version 2.2.3 on Linux Mint 19.2 MATE 64-bit
