### ISSUE TITLE
Floating Point Exception when attempting to print a specific file

### ISSUE THREAD

**Issue by kennethso168** [linuxmint/xreader#255]
```
 * Xreader version (xreader --version): 1.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Manjaro
```

**Issue**
The program force quits when I wanna to print my lecturer's presentation slides in pdf. After further investigation, it is a specific page of the slides that is the culprit and the error is `floating point exception (core dumped)` when run from the command line.

**Steps to reproduce**

* Testing file: 
[test.pdf](https://github.com/linuxmint/xreader/files/2450817/test.pdf) (Please only use this for debugging purpose, as I haven't seek permission from my lecturer. This is only one page of his slides though)
* Run from terminal `xreader test.pdf`
* File > Print
* The print settings probably won't matter too much as it crashes with different settings. But for the sake of testing I'll demonstrate with print to file for the following settings:
![screenshot from 2018-10-05 23-04-15](https://user-images.githubusercontent.com/5262487/46543322-1f261e00-c8f3-11e8-94eb-84ea0f61cba8.png)
![screenshot from 2018-10-05 23-04-41](https://user-images.githubusercontent.com/5262487/46543328-22b9a500-c8f3-11e8-8728-929ef3c31b1a.png)
![screenshot from 2018-10-05 23-04-59](https://user-images.githubusercontent.com/5262487/46543341-2816ef80-c8f3-11e8-853c-3fca89be8399.png)
* Click print

**Expected behaviour**
The file prints successfully

**Actual behaviour**
xreader force quit with the following message in the terminal:
`zsh: floating point exception (core dumped)  xreader test.pdf`

**Other information**

**Comment by Piiit** [comment]
@kennethso168 I tested your file on Linux Mint 19.1 with xreader 2.0.2 and could not reproduce your issue. Although, I am using bash and not zsh. Dunno if that makes a difference. Could you please test with a newer xreader version 2.0.2 or newer and see if your bug still persists?

**Comment by kennethso168** [comment]
Thank you very much for your testing. Unfortunately, I am no longer using xreader or any Linux distribution.
You can close the issue as you like.

**Comment by Piiit** [comment]
Thx, closing now
