### ISSUE TITLE
PDF from libreoffice not displayed properly

### ISSUE THREAD

**Issue by mabod** [linuxmint/xreader#258]
```
 * Xreader version 1.8.5
 * Manjaro testing
```

**Issue**

The second page of the PDF is empty. It should show a framed text box.

**Steps to reproduce**

Load the attached PDF file

**Expected behaviour**

It should show a framed textbox on the second page.

**Other information**

Okular is displaying the PDF just fine. The issue is with xreader and the gnome document viewer.

The PDF is attached here: 
[PDFtest.pdf](https://github.com/linuxmint/xreader/files/2566717/PDFtest.pdf)

The libreoffice file can be found here: [PDFtest.odt](https://www.dropbox.com/s/h4grahbeul99q5u/PDFtest.odt?dl=0)

**Comment by Piiit** [comment]
![Selection_051](https://user-images.githubusercontent.com/6096063/60213821-90807500-9864-11e9-8562-de35f1a8ccc4.png)

@mabod Xreader 2.0.2 seems to open this file correctly. Do you agree? Can we close this issue therefore?

**Comment by mabod** [comment]
Yes. Tested with xreader 2.0.2
