### ISSUE TITLE
Sidepane has too much white space and doesn't show the info well

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/xreader#259]
```
 * Xreader version (xreader --version)
1.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Arch
```

**Issue**
Xreader's default sidepane in Index mode doesn't show much text and most of the space is taken up by empty whitespace. Compared to EOG, Xreader is clearly less useful.

Example: Front window is Xreader, window in the background is EOG. Both are showing the Index of the same PDF. You can clearly see how poorly Xreader compares to EOG and how much less usable it is.

![screenshot from 2018-11-10 13-01-17-fs8](https://user-images.githubusercontent.com/7957590/48304567-75394300-e4e9-11e8-9fad-fb133e57635e.png)

**Steps to reproduce**
Open a PDF that has an Index and make sure your sidepane is in Index mode.

**Expected behaviour**
Show more information. Empty whitespace is useless. Yes, you can resize it but that's not a solution.

**Comment by JosephMcc** [comment]
I can see what the issue is from your screenshot. Is that specific pdf something you can share?

**Comment by JosephMcc** [comment]
Someone already submitted a PR to improve this: https://github.com/linuxmint/xreader/pull/235/commits/9cbee80cec0ab5ad81ced25950d55cbb2f21c37d

**Comment by nick-s-b** [comment]
@JosephMcc Thank you! The PDF is a textbook and it's huge. I can upload if it's absolutely necessary.

**Comment by Piiit** [comment]
@nick-s-b This seems to be solved. Do you agree?

**Comment by nick-s-b** [comment]
@Piiit Agreed! Solved!
