### ISSUE TITLE
XReader cannot open pdf from scanner with multiple pages

### ISSUE THREAD

**Issue by mhuberch** [linuxmint/xreader#260]
```
 * Xreader version 1.4.4
 * Linux Mint 18.2 Sonya 64-bit
```

**Issue**
Xreader pops up when opening the attached file which was created by scanning two blank A4-paper by a Ricoh scanner. However Xreader crashes after a while without any error message.

[ZweiSeitenGescannt.pdf](https://github.com/linuxmint/xreader/files/2590632/ZweiSeitenGescannt.pdf)

**Steps to reproduce**
Open the attached document which contains the scan of two blank A4-paper.

**Expected behaviour**
The document can be openend without problem using Adobe Acrobat Reader on Windows.

**Other information**
The problem only occurs, when a PDF file with more than one side is created by the Ricoh scanner. Onesided document can be openend as expected.

**Comment by Piiit** [comment]
![ZweiSeitenGescannt pdf_052](https://user-images.githubusercontent.com/6096063/60214153-3c29c500-9865-11e9-9e1f-a8c8ad891e49.png)

@mhuberch Xreader 2.0.2 opens this document without problems. Can we close this issue?

**Comment by Piiit** [comment]
@mhuberch It seems that this issue does no longer exist in recent xreader versions. Closing...
