### ISSUE TITLE
Cannot permanently hide toolbar

### ISSUE THREAD

**Issue by tobiasrenkin** [linuxmint/xreader#261]
```
 * Xreader version (xreader 1.8.5)
 * Distribution - (Mint)
```

**Issue**
Cannot permanently hide toolbar.

**Steps to reproduce**
Click view -> uncheck toolbar
Click edit -> save current settings as default
Exit Xreader and open it again.

**Expected behaviour**
Toolbar stays hidden.

**Other information**
The toolbar takes up way to much space.

**Comment by tobiasrenkin** [comment]
I think this is a bug, not a feature request.

**Comment by Piiit** [comment]
@tobiasrenkin Hi, I changed the label now, but there are no news now. However, this could be a good "first issue" to get started with contributing, if you like :-)

**Comment by icarter09** [comment]
Linux Mint 19.2 64bit
Xreader v2.2.3

I'm not able to reproduce this issue. The toolbar stays hidden when performing the steps to reproduce.

**Comment by harderj** [comment]
I can reproduce the issue. Try:
1. Open A.pdf
2. Hide toolbar
3. Save as default
4. Close
5. Open B.pdf

**Comment by icarter09** [comment]
@harderj you are correct. I didn't test it out with opening a different pdf. (Step 5).
