### ISSUE TITLE
Impossible to print

### ISSUE THREAD

**Issue by alcidejet** [linuxmint/xreader#262]
```
 * Xreader version (xreader 1.6.2.)
 * Distribution - (Mint 18.3 Cinnamon 64-bit)
```

**Issue**
I'ts impossible for me to print using Xreader and I don't know why. I'm forced to use another application (evince-previewer) and It works with all printers with. 

Any help pls ?

**Comment by Piiit** [comment]
@alcidejet Do other applications print correctly? Please provide more information.
