### ISSUE TITLE
Xreader keyboard shortcuts don't work without open document

### ISSUE THREAD

**Issue by gm10** [linuxmint/xreader#270]
**Describe the bug**
None of the Xreader keyboard shortcuts works until a document gets opened.

**To Reproduce**
1. Open Xreader
2. Press a keyboard shortcut, e.g. `Ctrl+W`

**Frequency**
Does the issue happen:
- [X] Always
- [ ] Randomly

**Edition (Desktop environment):**
In which edition is this happening?
- [ ] Cinnamon Edition
- [X] MATE Edition
- [ ] Xfce Edition

**Live or post-install:**
Indicate if this is happening after the installation, or during the live session:
- [X] Post-install
- [ ] Live session

**Comment by Piiit** [comment]
Fixed in master
