### ISSUE TITLE
Will not print more than one copy

### ISSUE THREAD

**Issue by netsecninja** [linuxmint/xreader#272]
```
 * Xreader version 2.0.2
 * Distribution - Mint 19.1 64-bit Cinnamon
```
**Issue**
When attempting to print multiple copies of a document, single page or multiple pages, only one document is printed. I am able to print multiple copies of documents from other programs correctly, so this does not seem to be a driver issue. 

**Steps to reproduce**
1. Open a PDF document with xreader
2. Select the file menu, then print
3. Increase copy count to more than 1
4. Click Print

**Expected behavior**
Print the same number of page copies as selected.

**Other information**
Master PDF Editor build 5.1.68 64-bit used as an example of a product that prints multiple copies properly.

**Comment by icarter09** [comment]
@netsecninja did the merged PR fix your issue?

**Comment by netsecninja** [comment]
Not sure, that was so long ago I don't remember how I fixed it. But thanks for the follow-up
