### ISSUE TITLE
Feature: go to page by number

### ISSUE THREAD

**Issue by fpohtmeh** [linuxmint/xreader#279]
Xreader 1.8.5
Linux Mint 19 Cinnamon. Cinnamon version: 3.8.9. Linux Kernel: 4.15.0-43-generic

Basic feature "go to page by number" is missing. User should scroll to reach a page by number.
Expected behaviour: Menu / Go / Page number / Input box.

**Comment by Piiit** [comment]
You can click on the textbox with page numbers or press Ctrl+L. Then hit Enter

**Comment by fpohtmeh** [comment]
This feature isn't obvious in UI. First of all, menus have no this shortcut. Second thing is the textbox, in my document it displays paragraph number, not page number. At same time clicking of page number control (for instance, 337 of 432) does nothing.

**Comment by mcp292** [comment]
`Ctrl+L` does it! But, this is not obvious. Maybe include "go to page" in the "Go" menu and show `Ctrl+L` next to it.

**Comment by icarter09** [comment]
I put up a PR that adds the `Go to Page` item to the `Go` menu and uses the same functionality as `Ctrl + L`.
