### ISSUE TITLE
Feature: recent documents

### ISSUE THREAD

**Issue by ErwinBaeyens** [linuxmint/xreader#282]
```
 * Xreader version (xreader --version) 2.0.2
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Fedora 28 Linux exl217 4.19.13-200.fc28.x86_64 #1 SMP Sat Dec 29 23:10:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Issue**
There is no recent documents menu item or way to quickly reopen a previously opened document.

**Steps to reproduce**
Start xreader direct, ie not by double clicking an existing document.  There is no way to open a previously opend doucument.  Always /

**Expected behaviour**
There should be a way fo open a previously opened document, either by a specific menu item in the file menu or as an option in the file selector after file Open ... or Ctrl O.  

**Other information**
I was under the impression that there was such a thing before but it seems to have gone away.  Removing features beyond the point where it becomes counter productive is not a good evolution.  That may be the core philosophy of Gnome, Cinnamon was started and became successful as a reaction against this gnome philosophy. Don't start to emulate them.

**Comment by Piiit** [comment]
Hi @ErwinBaeyens,
we have recent files implemented. It hasn't been changed... probably you have "Remember recently used files" disabled inside your "System Settings > Privacy" options. Please enable it and you will see recent files as thumbnails and under the "File" menu.

If it still does not show them, you have probably found a bug... please report back.

Cheers,
Peter

**Comment by ErwinBaeyens** [comment]
Indeed it works when switching on the global recent files used option is on.  
It may not be the best solution , As a photographer I go throug a lot of files on some day's and having a that as a global setting is not very handy. I want if for some applications like xreader or so but not for all files I open.

**Comment by Piiit** [comment]
@ErwinBaeyens Such a detailed configuration would need additional work on the privacy settings and underlying systems. I do not know where the actual backend is at the moment (maybe file a feature request for "cinnamon")...
However, it has nothing to do with xreader... please close this issue therefore. Thank you for your feedback.

**Comment by Piiit** [comment]
> However, it has nothing to do with xreader... please close this issue therefore. Thank you for your feedback.

This is an old discussion, and the feature request out of scope of xreader. See comments above...
