### ISSUE TITLE
I found that the index does not work in this version

### ISSUE THREAD

**Issue by sxdxyxy** [linuxmint/xreader#29]
When I navigate the file content using a index, the content does not move to the position what I  expect, so I  do not know any others have the same issue as me?

**Comment by Piiit** [comment]
This sometimes depend on your PDF, is the index working with other PDF readers? Could you please upload your test file?

**Comment by Piiit** [comment]
@sxdxyxy Hi, some news on this? Could you provide an example document? Is it PDF or another file format?

**Comment by Piiit** [comment]
Duplicate of #90
