### ISSUE TITLE
Search works bakwards in RTL languges (specifically Hebrew)

### ISSUE THREAD

**Issue by eladhen** [linuxmint/xreader#3]
Search in Xreader in Hebrew (and probably other right-to-left languages) doesn't work correctly. A search for a right-to-left word finds the opposite letter order. For example: if I search for the word שלום it won't be found. For the search to find it I have to search for םולש.

In other words, I have to enter the words backwards to search for them.

In the attached file you can see that I have to type האסידוא to find the word אודיסאה.

This seems to be quite an ancient bug in evince/poppler. Here are some bug reports:

The ancient and unfixed bug in poppler:
https://bugs.freedesktop.org/show_bug.cgi?id=2981

A thread with a possible solution, not implemented in 16.04 as far as I tried:
https://bugs.freedesktop.org/show_bug.cgi?id=55977

Some other bug reports relevant to this problem:
https://bugzilla.gnome.org/show_bug.cgi?id=546828
https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1009432

![xreaderbug2](https://cloud.githubusercontent.com/assets/12398651/15091280/b5068b66-144c-11e6-9a30-4b12c5ff61a6.png)

**Comment by clefebvre** [comment]
Thanks for this bug report. It looks like the cause of this bug isn't in evince, atril or xreader but in poppler itself. Apparently, it's been fixed upstream too https://bugs.freedesktop.org/attachment.cgi?id=119908.

I added the info on the LP bug report and made it affect poppler directly (it was reported against evince). https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1009432

Ubuntu might decide to apply the path or report the issue upstream to Debian.

**Comment by eladhen** [comment]
Clem, I've tried Evince 3.18.2 in Lubuntu 16.04, and the bug is fixed there. Please. can you implement that fix?

In the attached picture I'm searching for מדינת and Evince 3.18.2 is finding מדינת, as it should.


![screenshot from 2016-06-14 16 42 19](https://cloud.githubusercontent.com/assets/12398651/16045064/86cd7496-324f-11e6-80a3-51434ec6819b.png)

**Comment by eladhen** [comment]
Ok, scratch that. I just tried Xreader on Mint Cinnamon 18 beta and the Hebrew search there works as it should. I can only presume Ubuntu implemented the needed fix in poppler for the 16.04 base, so now it works, and it doesn't work in LMDE because it still uses the poppler version shipped with Jessie.

Sorry for the hassle, and thanks for everything. Mint is the best!
