### ISSUE TITLE
add shortkeys for zoom again: best fit / fit page width

### ISSUE THREAD

**Issue by voxspox** [linuxmint/xreader#30]
envice has shortkeys for zooming:

best fit => f
fit page width => w

please add these to xreader again.

**Comment by fernandoacorreia** [comment]
also dual => d

This doesn't sound like a complicated change, since the commands already exist on the menu.

Would you be open to a pull request implementing this?

**Comment by voxspox** [comment]
ok, I tried something.

**Comment by fernandoacorreia** [comment]
#57 looks good but I couldn't test it because I couldn't figure out how to build and run it. I created #59 for that.

**Comment by JosephMcc** [comment]
Closing since this is done.

**Comment by Piiit** [comment]
@JosephMcc Could you please reopen this issue, since the PR #57 has been reverted due to shortcut issues while searching.
