### ISSUE TITLE
Bad translation "Archvio"

### ISSUE THREAD

**Issue by sago104** [linuxmint/xreader#300]
```
 * Xreader version (xreader --version 2.0.2)
 * Distribution - (Mint 19.1)
```

**Issue**
Bad translation in "File". Language Spanish. 

![Selección_001](https://user-images.githubusercontent.com/19400469/55814584-79778580-5ab4-11e9-9339-668944e1d9ee.png)

**Comment by VaGNaroK** [comment]
To solve this only with the Spanish translation team.

> ```
>  * Xreader version (xreader --version 2.0.2)
>  * Distribution - (Mint 19.1)
> ```
> 
> **Issue**
> Bad translation in "File". Language Spanish.
> 
> ![Selección_001](https://user-images.githubusercontent.com/19400469/55814584-79778580-5ab4-11e9-9339-668944e1d9ee.png)

**Comment by Piiit** [comment]
@sago104 This would be a good first issue to get started with xreader development 😀

If you like read https://linuxmint-translation-guide.readthedocs.io/en/latest/index.html

...and become a member of a translation team. 

Cheers,
Peter

**Comment by icarter09** [comment]
This has been fixed upstream where the translation files are built. If you continue to see the issue, just let us know. Thanks.
