### ISSUE TITLE
Opening references in a new window shows a blank area

### ISSUE THREAD

**Issue by lukasfink1** [linuxmint/xreader#307]
```
 * Xreader version 2.0.2
 * Distribution - Arch
```

**Issue**
When right-clicking on a link (intra-document) in a PDF and choosing “Open in New Window” (or if middle-clicking on the link), xreader opens a new window on presumably the right page (as it shows in the top left) on presumably the same document (as the title says), but the document itself is not shown.

**Steps to reproduce**
1. Opening a PDF file containing references.
2. Right-clicking on a reference and choosing “Open in New Window”/Middle-clicking on a reference.

**Expected behaviour**
It should display the document on the new window instead of a blank area.

**Screenshot**
![Xreader displays a blank area where the document should be.](https://user-images.githubusercontent.com/3033969/57801456-08328e80-7754-11e9-9284-8eaa376cff92.png)

**Comment by icarter09** [comment]
Linux Mint 19.3 64bit
Xreader 2.4.3

I'm not able to reproduce this issue. When I 'right-click' on a reference, I only see `Open Link`. Clicking on that opens the link/reference in a new browser tab.

**Comment by lukasfink1** [comment]
That’s right. It’s seems to work again in Xreader 2.4.3.
