### ISSUE TITLE
Unimplemented annotation: POPPLER_ANNOT_STAMP, please post a bug report on Xreader

### ISSUE THREAD

**Issue by nadalle** [linuxmint/xreader#31]
Well, I opened a pdf (Sandman_Overture_Hugo_Packet.pdf) and got this warning:

`
** (xreader:15323): WARNING **: Unimplemented annotation: POPPLER_ANNOT_STAMP, please post a bug report on Xreader bug tracker (https://github.com/linuxmint/xreader/issues) with a testcase.
`

Unfortunately I can't include the PDF, since it's copyrighted.

**Comment by Piiit** [comment]
Another issue related to this: 
```
** (xreader:21627): WARNING **: Unimplemented annotation: POPPLER_ANNOT_FREE_TEXT, please post a bug report on Xreader bug tracker (https://github.com/linuxmint/xreader/issues) with a testcase.                                                                             
```

However, the file used is also copyrighted. Would be nice to create a PDF file with some annotations to use for future test cases.

**Comment by Piiit** [comment]
@nadalle @JosephMcc Hi, I have created a more complete bug report under #66, I think this issue can therefore be closed as duplicate.

**Comment by JosephMcc** [comment]
Ok.
