### ISSUE TITLE
Nemo-preview not working on Arch Linux

### ISSUE THREAD

**Issue by pawanneupane** [linuxmint/xreader#310]
I installed nemo-preview on Arch Linux, but nothing happens when I select a file and press space. Upon running it from the terminal I get:

Cjs-Message: 10:03:05.295: JS WARNING: [/usr/share/nemo-preview/js/viewers/text.js 31]: Requiring GtkSource but it has 2 versions available; use imports.gi.versions to pick one

(nemo-preview-start:3153): Cjs-WARNING **: 10:03:05.298: JS ERROR: Error: Requiring NemoPreview, version none: Requiring namespace 'GtkSource' version '3.0', but '4' is already loaded
@/usr/share/nemo-preview/js/viewers/text.js:33:7

/usr/bin/nemo-preview: line 15:  3153 Segmentation fault      (core dumped) /usr/lib/nemo-preview/nemo-preview-start

**Comment by leigh123linux** [comment]
Your issue belongs to https://github.com/linuxmint/nemo-extensions/issues
