### ISSUE TITLE
XReader 1.0.8 hangs when stat'ing recent files on unavailable network shares / places

### ISSUE THREAD

**Issue by x86dev** [linuxmint/xreader#32]
I'm experiencing frequent hangs if I'm opening XReader, either as standalone program (no file to display selected) or when opening files with it. After running XReader with strace, it shows that XReader spends a lot of time stat'ing the recent files, even on network shares or places which currently might not be available. This leads to the "hang", meaning XReader even won't show up until it's done with this enumeration, or, even worse, the UI freezes.

I'm using XReader 1.0.8 on Mint 18.
I did not find any options to disable enumerating for those recent files.

I see the following possible solutions here:
1. Give the user the chance to still use XReader while those recent file enumerations are done in the background as a separate task.
2. Add an option to disable the recent file feature altogether.
3. Add an option to skip recent files which are on remote / unreachable places.

Please let me know if you need any further details to solve this issue. Thanks.

**Comment by jcalcote** [comment]
This bug is still happening and it's very annoying - can anyone take a look at it? I'd be happy to provide any information required - I can reproduce it 100% of the time now on my system.

**Comment by jcalcote** [comment]
Additional information - when I start xreader, if I immediately start scrolling in the window, I can keep it working, but if I stop scrolling for a second or two, then it locks and I can no longer regain mouse control (although, I see the mouse events in the strace).

**Comment by icarter09** [comment]
@jcalcote you still experiencing this issue?

**Comment by icarter09** [comment]
Xreader v2.4.4
Mint 19.3 

I'm not able to reproduce this issue.
