### ISSUE TITLE
Compile without webkit2gtk

### ISSUE THREAD

**Issue by chazanov** [linuxmint/xreader#326]
My main reason for using xreader was that I could use it without the buggy & fat _webkit2gtk_ library.

May you please tell me the right config options to still achieve this with xreader 2.2.2?

**Comment by metadings** [comment]
This is true. xreader 2.0.2 takes up to 90,000g VIRTUAL bytes, due to starting a WebKitWebProcess and a WebKitNetworkProcess. No one else does so, not even Firefox or vscode.

I do recommend evince to you...

**Comment by Piiit** [comment]
@chazanov @metadings 
You can check compilation options via `meson configure debian/build/`. If you then disable `epub` support with `meson configure debian/build/ -Depub=false`, no webkit2gtk will be integrated.

Happy hacking :-)

**Comment by Soapux** [comment]
This bug was fixed is PR #335
