### ISSUE TITLE
No print icon in print preview window

### ISSUE THREAD

**Issue by martywd** [linuxmint/xreader#327]
```
 * Xreader version 2.2.3
 * Distribution - LM 19.2 Tina MATE 64-bit (upgraded from 19.1 using Update Manager)
```

**Issue**
Print 'Preview' window previously had a printer icon to allow printing the .pdf directly from the print preview window if one was satisfied with the preview.  Now in this latest xreader there is NO print icon in the print preview window which means after previewing what is to be printed, the user must close the print preview window and start the 'File|Print' process all over again.  Not real convenience!

**Steps to reproduce**
Open .pdf in xreader 2.2.3, then 'File|Print', click 'Preview' button, new print preview window of .pdf opens, no print icon in the tool bar at top of print preview window, no way to print .pdf from the preview window.  User must close preview window and start all over again.

**Expected behaviour**
To reiterate:  Previously in LM 19.1 MATE xreader had a print(er) icon in the top tool bar which when click on printed the previewed printing directly from the preview window which made much sense.

**Other information**
OT, but same issue with xviewer 2.2.1 as well.

**Comment by icarter09** [comment]
Linux Mint 19.3
Xreader v2.4.3

I'm not able to reproduce this issue. Followed the steps to reproduce, but the print icon was present on the Print Preview window.

**Comment by martywd** [comment]
> Linux Mint 19.3
> Xreader v2.4.3
> 
> I'm not able to reproduce this issue. Followed the steps to reproduce, but the print icon was present on the Print Preview window.

fwiw, my report was from almost 6 months ago for:
  * Xreader version **2.2.3**
 * Distribution - LM 19.2

So they've finally brought back the print icon in xreader **v2.4.3** print preview.    Outstanding!

I hadn't had an opportunity to print anything from xreader since upgrading to LM 19.3 earlier today.
Thanks for the heads up.

.
