### ISSUE TITLE
Repeated xreader-thumbnailer crash on parsing folders full of epubs

### ISSUE THREAD

**Issue by smurphos** [linuxmint/xreader#332]
```
 * Xreader version 2.23
 * Distribution - Mint 19.2 (Cinnamon)
```

**Issue**
xreader-thumbnailer fails to create a thumbnail for any epub file in my collection. mintreport shows a multitude of xreader-thumbnailer crashes.

Sample stacktrace - https://termbin.com/wxqd

This was a crash report from a epub sourced from http://www.ideal-group.org/cris-archives/sample_epub3_ebooks.htm

Link to file - http://files.infogridpacific.com/epub3/igpn-28languages-01-EPUB3.epub

**Steps to reproduce**
View a folder or search with nemo for epubs or test with the epub sample linked above.

**Expected behaviour**
Thumbnailer works and doesn't flood the system with crash-reports & coredumps.

**Other information**
Another user has reported similar issues here
https://forums.linuxmint.com/viewtopic.php?f=90&t=302666

**Comment by leigh123linux** [comment]
Please install libxreaderview3-dbg and libxreaderdocument3-dbg then reproduce and post the new backtrace as the old one has missing symbols.

**Comment by smurphos** [comment]
Here you go https://termbin.com/fjw0

**Comment by Piiit** [comment]
We are working on this. See #343

**Comment by smurphos** [comment]
Thanks @Piiit - nice to see a new person working on the codebase,
