### ISSUE TITLE
Can't build without Wayland

### ISSUE THREAD

**Issue by tarnh** [linuxmint/xreader#344]
```
 * Xreader version 2.4.2
 * Distribution - Arch
```

**Issue**
It's impossible to build xreader without Wayland.

I don't need wayland and use a mesa build without it (but otherwise the default ArchLinux package).

`../libdocument/ev-document-misc.h:32:10: fatal error: gdk/gdkwayland.h: No such file or directory`

Full error log: https://pastebin.com/aj4LyKdB

**Comment by leigh123linux** [comment]
Try removing the  gdk/gdkwayland.h includes  in libdocument/ev-document-misc.h as we don't support non standard use.
