### ISSUE TITLE
[Feature request] Please provide "Save" option

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/xreader#345]
```
 * Xreader version (2.4.2)
 * Distribution - (Fedora 30)
```

**Issue**
No "Save" option. Currently there is only "Save a Copy" option.

**Steps to reproduce**

**Expected behaviour**
After adding "annotations" tools PR, there should be a "Save" option beside "Save a Copy" option. Adding "Save" option is very necessary because without it user may be forced to create so many copies from same PDF each time adding new annotation ! 

**Other information**
It will be nice & very useful if you add 2 icons in toolbar: one for "Save" option & 2nd for "Save a Copy" option.

**Comment by icarter09** [comment]
Closed by #391
