### ISSUE TITLE
"Underline" & "Squiggly" appearing ABOVE the annotated text !

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/xreader#347]
```
 * Xreader version (2.4.2)
 * Distribution - (Fedora 30)
```

**Issue**
Currently changing type of annotations to "Underline" or "Squiggly" make them appear ABOVE selected text !

**Steps to reproduce**
Please open attached PDF on page 10, where I set 3 highlight annotations. It is an Arabic PDF. Change any one of them to "Underline or "Squiggly" & see where the new type appear !

**Expected behaviour**
They should appear bellow selected text.
[test.pdf](https://github.com/linuxmint/xreader/files/3936280/test.pdf)

**Other information**

**Comment by icarter09** [comment]
Xreader 2.6.4
Mint 20 64bit

Able to duplicate this issue for any given PDF.

**Comment by icarter09** [comment]
I've tracked this issue to being a problem with Poppler and not xreader.
