### ISSUE TITLE
Adding annotations not increase size of output file on Okular

### ISSUE THREAD

**Issue by Nokia808** [linuxmint/xreader#349]
```
 * Xreader version (2.4.2)
 * Distribution - (Fedora 30)
```

**Issue**
I noticed that adding annotations to a PDF (even if 1000 in number) using Okular will never cause any increment in the size of output PDF file ! But in xreader it will increase size of output PDF (but not huge. Something simple).
Is it possible to make xreader like Okular ?

**Comment by Piiit** [comment]
Okular does not store annotations inside the PDF. That is not a real PDF annotation and handled similarly as bookmarks in xreader. They would be lost when moving or renaming the file

**Comment by Piiit** [comment]
This is something we don't want
