### ISSUE TITLE
Upgrading to the latest linuxmint broke dbus interaction

### ISSUE THREAD

**Issue by antoine-levitt** [linuxmint/xreader#354]
The symptoms are identical to those in https://emacs.stackexchange.com/questions/41633/dbus-error-when-running-tex-evince-sync-view, but the cause is different (the proposed fixes did not work). Now the dbus FindDocument method does not return. It worked in mint 19.1. All three of evince, atril and xreader show the problem. It looks like the problem is with the daemon; the most related change I could find is https://github.com/linuxmint/xreader/pull/191. CC @Piiit 

With apologies if this isn't the right place to post this.

**Comment by antoine-levitt** [comment]
Thanks! Will this get into a linux mint upgrade, or should I build it from source? Also note that I have the same problem in evince and atril, so these might need a fix also.

**Comment by mtwebster** [comment]
It will be in a new version soon, but in the meantime, you can get the patched version here:
https://github.com/linuxmint/xreader/releases/tag/master.mint19

Download packages.tar.gz and extract the files to a folder, then install the packages via:
```
sudo dpkg -i *.deb
```
If you should get some sort of error over dependencies, do `sudo apt-get install -f`

You may want to temporarily ignore updates for that package in mintupdate, as it will want to re-install the official versions.
