### ISSUE TITLE
Build error: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: _gst_debug_min

### ISSUE THREAD

**Issue by SuperHeron** [linuxmint/xreader#356]
```
 * Xreader version 2.4.3
 * Distribution Exherbo Linux
```

**Issue**
Build fails because of 
`symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: _gst_debug_min`

**Steps to reproduce**
`meson -Depub=true`
`ninja -v -j1`

**Expected behaviour**
Build successful.

**Other information**
[xreader-2.4.3.log](https://github.com/linuxmint/xreader/files/4016115/xreader-2.4.3.log)

**Comment by leigh123linux** [comment]
Looks like /usr/lib/libwebkit2gtk-4.0.so.37 is to blame, it has a missing gstreamer symbol (_gst_debug_min)

**Comment by ernstlustig** [comment]
FYI:
Just installed TeamViewer which didn't run. Starting from terminal gave me:
`/opt/teamviewer/tv_bin$ ./TeamViewer
./TeamViewer: symbol lookup error: /lib/x86_64-linux-gnu/libQt5WebKit.so.5: undefined symbol: _gst_debug_min`
Looks more like some crippled dependency. I think I have to check my Qt5 installation.
