### ISSUE TITLE
Hot to keep Find bar opened?

### ISSUE THREAD

**Issue by tmelorc** [linuxmint/xreader#370]
```
 * xreader 2.2.3
 * Linux Mint 19.2 Tina
```

**Issue**
The Find bar closes when clicking anywhere in the pdf page.

**Steps to reproduce**

Press `ctrl+f` and search for a word. After finding it, click on any area of the pdf. 
The Find bar will close.

**Expected behaviour**
Keeps the Find bar opened until pressing `ctrl+f` again.

**Comment by icarter09** [comment]
Xreader 2.4.4
Mint 19.3

Was able to reproduce this issue. Looks like the issue revolves around the fact that the only way to close the Find bar once it's initiated is when a user clicks on any area of the PDF. I was expecting `ctrl+f` to toggle the Find bar, but that doesn't appear to be the case.

**Comment by rgreen5** [comment]
Xreader 2.8.3
Linux Mint 20.1

I don't know if this is helpful, but I can't duplicate the issue on my system. The Find bar stays open as expected until Ctrl + F is presed again.
