### ISSUE TITLE
Font not rendering correctly

### ISSUE THREAD

**Issue by phase7** [linuxmint/xreader#371]
```
 * Xreader version - 2.4.4
 * Distribution - Mint 19.3 Xfce 64bit
```

**Issue**
Correct font not loading. In my phone and on firefox browser I can see this pdf using times new roman but here it is showing some generic font.
#### From xreader
![Issue sshot](https://imgur.com/x1Xmkmv.png)
#### From Firefox 72
![sshot](https://imgur.com/6xmaVym.png)

_Can I force xreader to use other fonts?_

**Comment by icarter09** [comment]
@phase7 are you experienced this issue with other PDFs? If not, are you able to attach the PDF in question to this ticket? Thanks.
