### ISSUE TITLE
Hide/show side pane by default (setting)

### ISSUE THREAD

**Issue by Deleetdk** [linuxmint/xreader#373]
Don't know how to make a feature request, but here goes.

```
 * Xreader version 2.4.4
 * Distribution - Mint 19.3
```

**Issue**
The side pane is always shown whenever a file is opened. 95% of the time, it is not used by the user, and mostly closed to get more space.

**Steps to reproduce**
1. Open any file
2. Side pane appears

**Expected behaviour**
Have a setting about the default behavior. I suggest not showing the side pane by default, but having the option to enable it to open by default.

**Comment by okaestne** [comment]
You can disable the sidebar via the menu "View" > "Side Pane" and the "Edit" > "Save Current Settings as Default". It will then be hidden for all documents, that haven't been opened with Xreader yet.
