### ISSUE TITLE
Bookmarks - add name rather than simply page number

### ISSUE THREAD

**Issue by DaveC49** [linuxmint/xreader#376]
```
 * Xreader version (xreader --version) 2.4.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint19.3
```

**Issue**

Feature Request:

It would be useful to be able to give bookmarks a short descriptive name rather than just page numbers. Would make relocating to indexes, chapter starts, and specific information much easier.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by mickaelalbertus** [comment]
Hello @DaveC49 ,
You can rename your bookmarks with the left side panel (when you press F9), you choose bookmarks and you can rename its. Is it what you wanted to do?
