### ISSUE TITLE
Xreader 2.4.4 Print default value Bug

### ISSUE THREAD

**Issue by JeSuisEnPanne** [linuxmint/xreader#377]
```
 * Xreader version (xreader --version)
xreader 2.4.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
No LSB modules are available.
Distributor ID:	Linuxmint
Description:	LMDE 4 (debbie)
Release:	4
Codename:	debbie

```
how are you today ?

**Issue**
I use Xreader 2.4.4 to print the document: "doc1.pdf" on LMDE / 4.
[doc1.pdf] (https://github.com/linuxmint/linuxmint/files/4396944/doc1.pdf)

Print default value Bug on Canon TS5000-serie on A4 rendering "docbug.pdf".
[Docbug.pdf](https://github.com/linuxmint/linuxmint/files/4396945/Docbug.pdf)

**Steps to reproduce**
1.Open file : "doc1.pdf" double click
2. menu bar : File --> Print
3. to print
[doc1.pdf](https://github.com/linuxmint/linuxmint/files/4396944/doc1.pdf)

**Expected behaviour**
Corect print

**Other information**
I use LMDE 4 Debbie, my materials "doc-systemes.pdf"
[doc-systemes.pdf](https://github.com/linuxmint/linuxmint/files/4396946/doc-systemes.pdf)

bye bye

**Comment by leigh123linux** [comment]
I can reproduce the issue with evince or xreader with my Brother printer.
Try filing the issue against cups.
