### ISSUE TITLE
'Inverted Colors' won't be saved by 'Save Current Settings as Default'

### ISSUE THREAD

**Issue by hyajam** [linuxmint/xreader#38]
Each time when a new pdf file is opened the 'Inverted Colors' setting should be checked again.

Steps to reproduce:
1. Open a pdf file.
2. Check the 'Inverted Colors' in View > Inverted Colors.
3. Click the 'Save Current Settings as Default' in Edit menu.
4. Close the xreader window.
5. Open a pdf file again. (the same one or any other pdf file)

I don't know if it is intentional or it is a bug but in my opinion, this could be annoying especially when someone is using it for night reading.

**Comment by Cos-mo** [comment]
I confirm the problem.

As inverted colors get saved in evince in LM 17.3 I consider this as a bug.

**Comment by hub2git** [comment]
So happy this is fixed in Mint 18.2.
