### ISSUE TITLE
Problems with keyboard navigation and check-boxes on PDF forms

### ISSUE THREAD

**Issue by anjohnson** [linuxmint/xreader#380]
```
 * Xreader version 2.4.4
 * Distribution - Linux Mint 19.3
```

I'm using Xreader to fill in my [US tax return](https://www.irs.gov/pub/irs-pdf/f1040.pdf), and using the keyboard to navigate the fields of the PDF form (because I have lots of data to enter). This report may describe multiple bugs, but they all relate to interacting with a check-box using the keyboard.

Whenever I use the tab key to move the focus from a numeric field into a check-box, the box gets toggled immediately, without my doing anything. The focus then seems to move to the first field on the form. If that first field happens to be a check-box, pressing the Tab key again will toggle the state of that check-box, but it never moves the focus to the next field on the form, unlike the other field types.

**Steps to reproduce**

1. Download and open the [IRS 1040 form](https://www.irs.gov/pub/irs-pdf/f1040.pdf) in Xreader.
2. Click in the input box under "City, town or post office, state and ZIP code."
3. Note that the check-box labelled "You" to the right of that input box is initially unchecked.
4. Press the Tab key.
5. The check-box for "You" is now checked.
6. Note that the first check-box at the top of the form between "Filing Status" and "Single" is unchecked.
7. Press the Tab key.
8. The check-box for "Single" is now checked.
9. Press the Tab key.
10. The check-box for "Single" is now unchecked again.
11. Go to step 7 above…

**Expected behaviour**

Tabbing into a check-box should visually mark the box as being focused somehow but _not_ change its state. When it has the focus, pressing a key such as the Space bar should toggle the state, and leave the focus on the box. Pressing Tab should move the focus to the next field in order (I believe the order is programmed into the PDF file).

**Other information**

I appreciate the ability to enter form data using Xreader, thanks!

**Comment by icarter09** [comment]
Xreader v2.4.4
Mint 19.3 64bit

Was able to reproduce this issue.

**Comment by anjohnson** [comment]
One more probably related behavior: When using the tab key to move from a text/number input box to a check-box, the text entered doesn't seem to get properly re-displayed using the form font. I'm not a GUI programmer but I expect there's some behavior expected by the focus-change (focus-leave?) event which isn't being fired properly in the previous widget to do that.

**Comment by icarter09** [comment]
@anjohnson I put up a PR that should address most of your issues. This mirrors the functionality that is supported by Evince. The only thing that still needs to be done is to visual mark a checkbox when it has become the focused element. I'll probably make a feature request ticket for that and address via the new ticket. Let me know if this help.s

**Comment by anjohnson** [comment]
@icarter09 It looks like you did fix the text re-display on focus-change behavior described in my subsequent comment, but not the issues described in the original bug report when using the Tab key to move into and out of check-box widgets.
