### ISSUE TITLE
Powers not displayed

### ISSUE THREAD

**Issue by atsteich** [linuxmint/xreader#385]
```
 * Xreader version (xreader --2.4.4)
 * Distribution - (Mint 19.3)
```

**Issue**
Some powers of numbers are not shown in pdf's That must be fixed quickly, I was reading some paper, and text was completely wrong, because of the missing powers!
I have created a single page document, where the error occurs in some lines. For comparison open the document with chrome, or an other viewer.

As long as this is not fixed, xreader is absolutely unusable!!!

**Steps to reproduce**
I have added a [test.pdf](https://github.com/linuxmint/xreader/files/4545190/test.pdf) File, where the error occurs in 2 lines. For comparison open the document with chrome.

Errors in:
a)
d)

**Expected behaviour**

**Other information**

**Comment by Piiit** [comment]
The same holds in Evince... Might be a poppler bug

**Comment by Piiit** [comment]
Could you please check it is the same in Okular?

**Comment by atsteich** [comment]
> Could you please check if it is the same in Okular?

Same Same in Okular (1.3.3)

**Comment by Piiit** [comment]
@atsteich Thanks for testing, I fear that this bug is out of scope for xreader, since it comes from the underlying PDF library called poppler, which is used in all those applications we tested.

I am really sorry to close this issue here. Could you check if the poppler issue tracker has this bug report already, and maybe report there.

Wish you good luck!

**Comment by atsteich** [comment]
> @atsteich Thanks for testing, I fear that this bug is out of scope for xreader, since it comes from the underlying PDF library called poppler, which is used in all those applications we tested.
> 
> I am really sorry to close this issue here. You could check if the poppler issue tracker has this bug report already, and maybe report there.
> 
> Wish you good luck!

No problem, thanks for your help! I will report if I find something.
