### ISSUE TITLE
xreader crash on epub search - reproducable

### ISSUE THREAD

**Issue by artofit** [linuxmint/xreader#398]
```
 * Xreader 2.4.4
 * Manjaro XFCE 20
```

**Issue**
Crashes when search on an epub file (attached), just rename it .epub instead of .zip(due to upload constraints)

**Steps to reproduce**
1/ In terminal type: xreader.
xreader launches, but with errors:
`$ xreader

(xreader:2172): Gtk-CRITICAL **: 12:29:32.213: _gtk_css_image_get_concrete_size: assertion 'default_width > 0' failed

(xreader:2172): Gtk-CRITICAL **: 12:29:32.213: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed
`
2/ Open the epub file, the epub files opens without apparent issue.
in terminal, notice further errors, same type as xreader bare launch.

3/ In Xreader type: CTRL+F to launch the search box.
key in: "f"
It crashes
Terminal shows:
`(xreader:2172): Gtk-CRITICAL **: 12:29:44.697: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed
/tmp/xreader-2172/Escoffier - Le Guide culinaire.epub2TB8K0/OEBPS/Ib_Beurres.html:42: parser error : Opening and ending tag mismatch: br line 41 and dfn
</dfn>
      ^
/tmp/xreader-2172/Escoffier - Le Guide culinaire.epub2TB8K0/OEBPS/Ib_Beurres.html:67: parser error : Opening and ending tag mismatch: br line 41 and div
    </div>
          ^
/tmp/xreader-2172/Escoffier - Le Guide culinaire.epub2TB8K0/OEBPS/Ib_Beurres.html:285: parser error : Opening and ending tag mismatch: br line 41 and body
</body></html>
       ^
/tmp/xreader-2172/Escoffier - Le Guide culinaire.epub2TB8K0/OEBPS/Ib_Beurres.html:285: parser error : Opening and ending tag mismatch: br line 41 and html
</body></html>
              ^
/tmp/xreader-2172/Escoffier - Le Guide culinaire.epub2TB8K0/OEBPS/Ib_Beurres.html:285: parser error : EndTag: '</' not found
</body></html>
              ^
Erreur de segmentation (core dumped)
[toshpc@toshpc ~]$`

**Expected behaviour**
No crash, as Calibre, Okular, etc. on same file
[Escoffier - Le Guide culinaire (seach bug in Xreader244).zip](https://github.com/linuxmint/xreader/files/4681604/Escoffier.-.Le.Guide.culinaire.seach.bug.in.Xreader244.zip)

**Other information**

**Comment by artofit** [comment]
>I solve this bug.
Unfortunately, no it still crashes for me with 2.6.1

`$ xreader

(xreader:2470): Gdk-WARNING **: 21:30:06.257: ../gtk/gdk/x11/gdkwindow-x11.c:5633 drawable is not a native X11 window

(xreader:2470): Gdk-WARNING **: 21:30:06.257: ../gtk/gdk/x11/gdkwindow-x11.c:5633 drawable is not a native X11 window

(xreader:2470): Gdk-WARNING **: 21:30:06.257: ../gtk/gdk/x11/gdkwindow-x11.c:5633 drawable is not a native X11 window

(WebKitWebProcess:2698): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(WebKitWebProcess:2671): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(WebKitWebProcess:2671): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(WebKitWebProcess:2698): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(WebKitWebProcess:2671): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(WebKitWebProcess:2698): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:71:36: The style property GtkCheckMenuItem:indicator-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(WebKitWebProcess:2671): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

(WebKitWebProcess:2698): Gtk-WARNING **: 21:30:07.713: Theme parsing error: gtk.css:76:30: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version
/tmp/xreader-2470/Escoffier - Le Guide culinaire.epubYR2VL0/OEBPS/Ib_Beurres.xhtml:42: parser error : Opening and ending tag mismatch: br line 41 and dfn
</dfn>
      ^
/tmp/xreader-2470/Escoffier - Le Guide culinaire.epubYR2VL0/OEBPS/Ib_Beurres.xhtml:67: parser error : Opening and ending tag mismatch: br line 41 and div
    </div>
          ^
/tmp/xreader-2470/Escoffier - Le Guide culinaire.epubYR2VL0/OEBPS/Ib_Beurres.xhtml:285: parser error : Opening and ending tag mismatch: br line 41 and body
</body></html>
       ^
/tmp/xreader-2470/Escoffier - Le Guide culinaire.epubYR2VL0/OEBPS/Ib_Beurres.xhtml:285: parser error : Opening and ending tag mismatch: br line 41 and html
</body></html>
              ^
/tmp/xreader-2470/Escoffier - Le Guide culinaire.epubYR2VL0/OEBPS/Ib_Beurres.xhtml:285: parser error : EndTag: '</' not found
</body></html>
              ^
Erreur de segmentation (core dumped)
[lkde@lkde-tosh ~]$ `

**Comment by mickaelalbertus** [comment]
It works with the last version of master of xreader, I just retest it to be sure :)  If you want to try it you have to download and compile the software. I don't know when it will be published.

**Comment by artofit** [comment]
>It works with the last version of master of xreader,
2.6.1 is not the latest?
Might be an idea to add the iso date to the version

**Comment by icarter09** [comment]
@artofit are you still experiencing this issue? The version of xreader you are using now (if it's the latest) should have the fix for this issue.

**Comment by artofit** [comment]
Yes fixed since 2.6.2 if I recall correctly, well at least in 2.6.4
thanks
