### ISSUE TITLE
Xreader doesn't display epub on LMDE 4

### ISSUE THREAD

**Issue by Maik-aD** [linuxmint/xreader#401]
```
 * Xreader version (2.4.4)
 * Distribution - (LMDE 4)
```

**Issue**

I have a epub file but Xreader on LMDE 4 only shows the index and doesn't load the pages at all. I tested xreader on other distro's via a live usb stick session that ship with the same version of xreader as in LMDE4 which is 2.4.4.. On Fedora 32 Xfce and Cinnamon Xreader works as should. So the epub file is fine and thus not corrupted

On Debian 10 buster Xfce, also from a usb live session, i tried Atril which also correctly loads the epub, so i thought i install Atril on LMDE4 but get the same problem of the epub not loading. This makes me guess it's a issue within LMDE 4. 

I also tried Xreader with the same epub file on LM 19.3 Cinnamon and updated Xreader to the latest version (2.4.4) in the live session. The epub file loads correctly.

Since i bought this epub/ebook via the website of a bookstore, i am not allowed to share the file due copyright reasons.

**Steps to reproduce**

**Expected behaviour**

**Other information**
I ran Xreader via the terminal opening the epub on LMDE 4 and got this error message:
`** (xreader:1909): WARNING **: 16:18:34.641: Error loading data from file:///tmp/xreader-1909/9789045354569-5ec8a7f071a77.epubMNJVL0/OEBPS/5ec8a7f071a770.html: Frame load interrupted
`

**Comment by mickaelalbertus** [comment]
I think it is linked to bug #266  which is linked, seemingly, to a bug of libweb2gtk (html pages are no more handled - for example with epiphany I can't open html pages). It is solved by PR #389
