### ISSUE TITLE
Feature request: Index in side pane showing whole title

### ISSUE THREAD

**Issue by a-kbd** [linuxmint/xreader#404]
Would be neat if the titles in the index of the side pane showed all of the title, no matter the width of the side pane. For some indexes making the side pane super wide takes too much space

Current            |  Desired
:-------------------------:|:-------------------------:
![current](https://user-images.githubusercontent.com/63161225/86158102-98729500-bb08-11ea-90b5-f0fed198e7b0.png) |   ![desired](https://user-images.githubusercontent.com/63161225/86156483-50527300-bb06-11ea-92de-f43f2338acc3.png)

**Comment by icarter09** [comment]
I'm thinking a button at the bottom of the `Index` section that toggles between the settings would work best to implement this feature. This would follow the format of the other Side Pane options, as well giving users the option to choose when they would like it applied.

**Comment by icarter09** [comment]
I put up a PR that replaces the default functionality to show the whole title. The more I played around with this, the more I liked having the whole title displayed v/s the ellipsis. I might double back to make this an option in the future if a request is made.
