### ISSUE TITLE
mouse wheel no longer works in page view

### ISSUE THREAD

**Issue by WikiSteve** [linuxmint/xreader#405]
```
 * Xreader version (2.6.4)
 * Distribution - (Upgraded from Mint 19.3 to 20)
```

**Issue**

When in page view mode on Mint 19.3 and earlier I was able to use the scroll wheel to move through pages.  I no longer can.

**Steps to reproduce**
Upgrade to Linux Mint 20.

**Expected behaviour**

To be the same as the previous version and be able to scroll through the document in page view.  The mouse wheel still works in reader view however.

**Other information**
I use Xreader when doing presentations.  I set Xreader to page view and with a wireless mouse I use the scroll wheel to change slides (ppt that are exported to pdf).  I no longer can do that and need to use the left and right arrow keys on the keyboard.

**Comment by ElectronicBattle** [comment]
Same here - I upgraded from LM19.3 (Mate) to LM20 (Mate) on 24/7/20 and my symptoms and problems are as per the original post from WikiSteve.  I further checked by using the icons and also the xreader keyboard shortcuts thus:

ctrl+1 ... reader view, mouse works as before
ctrl+2 ... page view and I now need to use the pg up and pg down keys to move ...mouse wheel no longer functions

(ctrl+mouse wheel causes page zoom)

**Comment by ElectronicBattle** [comment]
Excellent work, Clem ... today's update for LM20.1 has installed v 2.8.3. and the mouse wheel is working once again. Thanks very much!
