### ISSUE TITLE
CTRL + LEFT/RIGHT Should NOT Work When a Text Field is Focused

### ISSUE THREAD

**Issue by machineghost** [linuxmint/xreader#407]
```
 * Xreader version (xreader --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

CTRL + LEFT/RIGHT should NOT work when you are focused on a text input in a form fillable PDF

**Steps to reproduce**

1. Open any form fillable PDF
2. Focus on a text field
3. Hit CTRL + LEFT/RIGHT to go to the previous/next word within that field

**Expected behaviour**

You go to the previous/next word.  But instead, the page rotates!  It should not trigger that keyboard shortcut when editing text: no one wants to rotate their PDF, they're just trying to go to move around the text.

**Other information**

**Comment by icarter09** [comment]
Xreader v2.6.4
Mint 20

@machineghost are you still experiencing this issue? I wasn't able to duplicate the issue. Using `CTRL + Left/Right` would go the the previous/next word as intended from a text field that was in focus on a fillable form.

**Comment by machineghost** [comment]
I recently upgraded to Mint 20 myself actually, and now I no longer experience the issue.
