### ISSUE TITLE
Opening find box causes crash

### ISSUE THREAD

**Issue by a-torgovitsky** [linuxmint/xreader#410]
```
 * Xreader version (xreader --version)
2.6.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20
```

**Issue**
Crashing when opening the find search bar with Ctrl + F

**Steps to reproduce**
Ctrl + F
type something that matches. For example in the attached PDF, you can type "synthetic"
[li2019jotasa.pdf](https://github.com/linuxmint/xreader/files/5071831/li2019jotasa.pdf)
without clearing the match, repeatedly hit Ctrl + F
The search bar box will open and close and crash usually after 1--3 iterations

**Expected behaviour**
Open and close the search bar without the program crashing

**Other information**
If I run from the command line, it shows a segfault on exit

**Comment by icarter09** [comment]
@a-torgovitsky are you experiencing this issue on other PDFs? I'm noticing that some PDFs duplicate this issue while others do not.

**Comment by a-torgovitsky** [comment]
Yes I'm definitely experiencing it with other PDFs. Certainly the majority
that I try. Do you want to post the one where you do not see the behavior,
and I can try that one?

**Comment by icarter09** [comment]
Here's a PDF for you to try out. I'm not able to duplicate the issue with it. I'm definitely running into the issue with a majority of the PDFs I have tried. 
[bitcoin.pdf](https://github.com/linuxmint/xreader/files/5146266/bitcoin.pdf)

**Comment by icarter09** [comment]
@a-torgovitsky I put up a PR for this issue. I was able to fix the issue by removing the search text when the find bar is removed/disabled, which is what Evince looks to be doing as well. If you aren't a fan of the fix, just let me know and we'll go from there. But at least it does address the issue and should no longer cause a segfault while using Xreader.

**Comment by a-torgovitsky** [comment]
I am also not able to duplicate the issue with bitcoin.pdf.
The proposed fix seems good to me. Thanks for looking into this!
