### ISSUE TITLE
Manga page switch

### ISSUE THREAD

**Issue by FromRightToLeft** [linuxmint/xreader#413]
```
 * Xreader version 2.6.4
 * Distribution - Mint 20 Cinnamon
```
Hello,

I would like to request a new feature that would enhance reading from right to left. 

Some manga look better in Dual (Even pages left) some in Dual (Odd pages left), but the left and right pages are always flipped. What I mean by this is that the first page to be read is always on the left, and when you read manga you want that page to be on the right. 

I would like to post screenshots to illustrate the problem, but don't want to infringe on copyright.

I would like an option to switch left and right pages on top of both Dual viewing modes: a feature I call Manga page switch.

Thank you

**Comment by icarter09** [comment]
Check out [Peek](url). That might help you in recording you opening a page or two and displaying the issue. From there we can step on the exact functionality. Thanks.

**Comment by FromRightToLeft** [comment]
Sorry, but I'm traveling and I have very limited access to the internet, because where I am internet is very expensive. On top of that there are those pesky copyrights. 

The best I can do for now is this:
I believe these two screenshots demonstrate the problem I’ve described above. They come from the same manga, but from two different editions. I’ve marked which page should be on the left and right for your covariance. You can clearly see boy’s leg and girl’s hand would connect with the rest of their bodies if the outer edges become the inner edges. Please note how different Dual settings make different editions display correct pages as adjacent albeit in the wrong order, as demonstrated by the menus.

Hope this helps
![Eng](https://user-images.githubusercontent.com/70649250/98575387-70b2eb00-22b9-11eb-931b-98b2cebca03f.jpg)
![Jap](https://user-images.githubusercontent.com/70649250/98575400-74df0880-22b9-11eb-828b-bcf331534137.jpg)

**Comment by icarter09** [comment]
@FromRightToLeft thanks for the pics and explanation!

**Comment by icarter09** [comment]
@FromRightToLeft to make sure I'm correct in my thinking, as setting like "Dual (Even pages on the left)" would work except that Xreader is not starting out with page 2 next to page 1. That correct?  I don't have any Manga to test with to double check.

**Comment by FromRightToLeft** [comment]
If by "not starting out" you mean page 2 is on the right, when it should be on the left, then yes. But what's up with manga that displays adjacent pages like this in "Dual (Odd pages left)"? Before you ask: if you use the wrong Dual option adjacent pages are no longer neighboring and it's a mess.

**Comment by icarter09** [comment]
Yeah so with any PDF, "Dual (Even pages left)", it puts page 1 on the left, but page 2 is not left of page 1, but rather page 2 is started on the next line, and then page 3 is to the right of it. Currently the space next to page 1 is empty in this setting.

Using "Dual (Odd pages left), would never work for Manga since it's completely backwards for what the layout should be. 

Believe we are saying the same thing that the correct way for Xreader to view/open Manga would be "Dual (Even pages left)", but with page 2 next to page 1. That should carry over to the rest of the pages with page 3 on the left and page 4 on the right...and so on. 

Sure you have plenty of PDFs, but I've attached one just in case (non-Manga) for you to view for testing. Thanks.
[bitcoin-whitepaper.pdf](https://github.com/linuxmint/xreader/files/5526062/bitcoin-whitepaper.pdf)

**Comment by FromRightToLeft** [comment]
"Using "Dual (Odd pages left), would never work for Manga" - but it does, I've proven it in the screenshots above. 

We need both Dual modes for manga, and I think I know why that is. Two reasons: 1. Cover is essentially an additional page; 2. There is a varied number of pages between cover and proper manga (advertisements, notes, extras etc.). Look at example manga above, the Japanese edition has 5 non-manga pages (including cover) before actual manga begins that's why "Dual (Odd pages left)" displays correct pairs of adjacent pages. For English edition there are 8 non-manga pages (including cover) and that's why "Dual (Even pages left)" works best. 

And that's why Xreader needs a toggle switch to swap pages in both Dual modes.

Thanks

**Comment by icarter09** [comment]
Got ya. Sorry for all the questions. Have never read any Manga or have any files to properly test with.

**Comment by FromRightToLeft** [comment]
This is publisher's fault, and I bet some western books have this problem too, so they align in "Dual (Even pages left)". You just never noticed, because it matters only in books with double-page spread illustrations. This is why changing the way "Dual (Even pages left)" works could actually create another problem. I argue we need 4 different reading modes for Dual, and the simplest way to implement this is through a toggle switch to swap left and right pages, or so I think. Hence I have written, what I have written in the OP ^_^

**Comment by FromRightToLeft** [comment]
OK! I've got it! I know now how to explain this in the simplest way possible. I could be wrong, but I believe what we are trying to accommodate here are 4 types of books.

1. Books read left to right that begin with an odd numbered page (LRO)
2. Books read left to right that begin with an even numbered page (LRE)
3. Books read right to left that begin with an odd numbered page (RLO)
4. Books read right to left that begin with an even numbered page (RLE)

You say you've never read any Manga. Maybe, you could create some PDFs in LibreOffice to simulate different book types and experiment with them?

Good luck!

**Comment by FromRightToLeft** [comment]
I would like to thank you. After upgrading the system I immediately lunched Xreader and it works like a dream! :smile: 

If I could make a final suggestion, would you consider changing the name of this feature in the menus? I feel like "Right to Left" doesn't really tell people what it does, and I have a suspicion that it might be useful with some western books as well. "Switch right and left pages" maybe? 

Thanks again and take care
