### ISSUE TITLE
xreader compilation failed on openSUSE. Possible bug in shell/ev-window.c

### ISSUE THREAD

**Issue by kevinsmia1939** [linuxmint/xreader#418]
Hello,

I am trying to update to xreader 2.6.4 on openSUSE factory. However, I get an error when building xreader.

```
[  142s] ../shell/ev-window.c: In function ‘sizing_mode_to_string’:
[  142s] ../shell/ev-window.c:373:1: error: control reaches end of non-void function [-Werror=return-type]
[  142s]   373 | }
[  142s]       | ^
[  142s] At top level:
[  142s] ../shell/ev-window.c:5801:1: warning: ‘menubar_deactivate_cb’ defined but not used [-Wunused-function]
```

I was suggested that the issue could be shell/ev-window.c

https://github.com/linuxmint/xreader/blob/06ff66b775d610e1083273839d0b01e6fe3dcb30/shell/ev-window.c#L363

It expects an enumeration and will return a string. So if it does not get anything that is not a member of enumeration it will break.

Dependencies installed

```
gcc-c++ 10
gnome-common-3.18.0
intltool-0.51.0
itstool-2.0.6
libappstream-glib8-0.7.17
libtiff-devel-4.1.0
mathjax-2.6.0
meson-0.55.1
ninja-1.10.1
texlive-devel-2020.171
yelp-tools-3.32.2
ddjvuapi 3.5.27
gail-3.0 3.24.22
gio-2.0 2.64.4
glib-2.0 2.64.4
gobject-introspection-1.0 1.64.1
libgthread-2_0-0-2.64.4
gtk+-3.0 3.24.22
gtk+-unix-print-3.0 3.24.22
kpathsea 6.3.2
libgxps 0.3.1
libsecret-1 0.20.3
libspectre 0.2.9
libtiff-4 4.1.0
libxml-2.0 2.9.10
poppler-glib 0.90.0
sm 1.2.3
webkit2gtk-4.0 2.28.4
xapp 1.6.10
zlib 1.2.11
```

**Comment by dcermak** [comment]
I would suggest to add a `default` case with a `g_assert_not_reached();` to the switch in https://github.com/linuxmint/xreader/blob/06ff66b775d610e1083273839d0b01e6fe3dcb30/shell/ev-window.c#L365

**Comment by kevinsmia1939** [comment]
> I would suggest to add a `default` case with a `g_assert_not_reached();` to the switch in
> 
> https://github.com/linuxmint/xreader/blob/06ff66b775d610e1083273839d0b01e6fe3dcb30/shell/ev-window.c#L365

Hello,

Thanks for the patch, I apply the patch and build of factory pass now.
