### ISSUE TITLE
First page on left in dual page view mode

### ISSUE THREAD

**Issue by reaganch** [linuxmint/xreader#42]
When I switch to dual page view mode, the first page starts on the right, leaving an ugly empty gap on the left. Evince used to have a handy "first page on left" option. This would be really useful if implemented, considering both aesthetics and usability. I am running Xreader on a fresh install of Linux Mint 18.

**Comment by Piiit** [comment]
@JosephMcc @reaganch Implemented :-) Please close...

**Comment by JosephMcc** [comment]
Done :)
