### ISSUE TITLE
segv while adding annotations

### ISSUE THREAD

**Issue by jeanjjgm** [linuxmint/xreader#422]
```
 * Xreader version 2.6.4 also 2.4.4
 * Distribution - Mint 19.3
   amd64
```

**Issue**
Using annotation tools highlight and add note cause segment violation.

**Steps to reproduce**
- Open a pdf : ex xreader test.pdf
- Add an annotation hightlight (ex: 1 word somewhere)
- Add 2 annotation notes (with or without text inside) by right clicking on the hightlighted zone
- delete hightlight annotation (one of the note may slightly move)
- delete one note annotation

**Expected behaviour**
First UI freeze then segment violation error.

**Other information**
I have tested with different pdf. It doesn't matter. Just need a string to hightlight inside.
For instance this [file](https://framadrop.org/lufi/r/FCcmZVtc79#DWvFDB8yE4UYD/p7QAmzLMAhoz/rK6imqK3F4e4SRB0=)

**Comment by icarter09** [comment]
Xreader 2.6.4
Mint 20 64bit

Was able to reproduce the issue.

**Comment by icarter09** [comment]
@jeanjjgm I put up a PR that should fix this issue. Let me know if it doesn't work for you. Thanks.

**Comment by jeanjjgm** [comment]
Yes it fix the issue, nice !
