### ISSUE TITLE
translation wrong in the spanish version 

### ISSUE THREAD

**Issue by stranger01** [linuxmint/xreader#431]
![Captura de pantalla de 2020-11-05 19-11-46](https://user-images.githubusercontent.com/40051149/98310389-c5452600-1f9a-11eb-9357-60b9b21359b4.png)
```
 * Xreader version (xreader --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

**Steps to reproduce**
open the actual xreader in spanish

the first option
is archvio

**Expected behaviour**

the correct translation should be : archivo

**Other information**

**Comment by NikoKrause** [comment]
Are you using Spanish (Colombia) by any chance?

**Comment by icarter09** [comment]
@stranger01 This has been fixed upstream where the translation files are built. If you continue to see the issue, just let us know. Thanks.
