### ISSUE TITLE
FFS KEEP STILL !

### ISSUE THREAD

**Issue by jonshouse1** [linuxmint/xreader#435]
Linux Mint 20 XFCE 64 bit

How the FUCK  can anyone think this behaviour is USEFUL ?

It stops me doing any real work with PDF documents as the moment I change context to an editor what I am looking at for reference scrolls away !

I've resorted to reading PDFs on my Ipad while I code.

This was filed as a bug two years ago and marked "Fixed".

Does not look "fixed" to me.  It is BEYOND annoying, more importantly how can anyone sane think this is USEFUL ?

Is this XFCE window manager? Is this XREADER?   Where is this living hell coming from?  I am not the only one who keeps posting this yet nobody seems interested in fixing it for real ! 

https://youtu.be/6s4EUEWuSpE

**Comment by leigh123linux** [comment]
If you can post without swearing try filing the issue again.
