### ISSUE TITLE
Crash on Reload

### ISSUE THREAD

**Issue by reaganf2** [linuxmint/xreader#44]
Xreader crashes with a segmentation fault when I hit Reload (Ctrl+R) while viewing a PDF. Running Xreader on a fresh install of Linux Mint 18.

**Comment by Piiit** [comment]
@reaganf2  Hi, I cannot reproduce this issue. Does it happen with every PDF or just some. If so, could you upload a PDF file that causes this SEGFAULT.

**Comment by wylebe** [comment]
I am having the same issue, and it's very random. It usually happens to me when a PDF is already open in Xreader and an updated version is exported from LibreOffice.

**Comment by reaganf2** [comment]
It happens most of the time, and seems to not be dependent on the individual PDF. At times, the same PDF has and has not segfaulted upon reload.

**Comment by Piiit** [comment]
@reaganf2  @wylebe I think this is a duplicate of #25 and #33 which has already been fixed with patch #28.
Could you please check if this patch also fixes your issue?

**Comment by reaganf2** [comment]
I'm using the current version from the LM18 repo: v1.0.8.
Not quite sure if this contains the patch.

**Comment by reaganf2** [comment]
I can confirm that building the latest version fixed this problem.

**Comment by Piiit** [comment]
Perfect. Please close the issue... 

Thx for reporting
