### ISSUE TITLE
'Save a copy' closes the reader, with at least one particular PDF-format file

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/xreader#444]
```
 * Xreader version (xreader --version) 2.6.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20 Cinnamon x64
```

**Issue**

With at least one PDF file, 'save a copy' closes it with no error message and nothing in the syslog.

**Steps to reproduce**

1. Get [this file](https://www.lua.org/gems/sample.pdf).
2. Open with the Reader.
3. Save a copy.
4. See that the Reader closes.

**Expected behaviour**

Obviously not 4.

**Other information**

**Comment by icarter09** [comment]
I'm not able to reproduce this issue. Was able to "Save a Copy" with no issues.

**Comment by LinuxOnTheDesktop** [comment]
I should have further specified what I was doing. _I get the crash - on two computers - if and only if I do the following. Point Firefox at the file and tell Firefox to open it with the Reader_ - and then save a copy.

I do not get the crash if I download the file to my desktop and then open it with the Reader (and then save a copy). I have not been able to see whether the problem - the problem with what we might call 'direct opening' - happens with a Chromium based browser, because such browsers (the ones I have, anyway) always open the file with their own inbuilt pdf reader.

**Comment by amo-f77** [comment]
Can confirm that this behaviour has been happening for months. Any pdf downloaded and opened from Firefox (incl 83.0), will always close Xreader when save a copy is performed.
Xreader 2.6.4 on Linux Mint 20, Cinnamon 4.6.7

**Comment by hreba** [comment]
Another confirmation. Here, xreader (standard version from repository) always behaves this way. 'Here' meaning:
Linux Mint 20
Xfce4
AMD Ryzen 5 PRO 3400G

**Comment by icarter09** [comment]
I've found the issue that causes this ticket and coming up with a best solution to apply for a fix.

**Comment by icarter09** [comment]
I've put up a PR for this issue. If the issue still persists, just let me know. Thanks.
