### ISSUE TITLE
Everytime I open the xreader window it appears in a different position even when closed MAXIMISED last time

### ISSUE THREAD

**Issue by ghost** [linuxmint/xreader#447]
```
 * Xreader version (xreader --version)
2.6.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20
```

**Issue**
Everytime I open the xreader window it appears in a different position even when closed MAXIMISED last time

**Steps to reproduce**
Open document
Maximise
Close document
Reopen more docuemnts

**Expected behaviour**
Window to retain last position of maximised

**Actual behaviour**
Windows goes for a tour all over the place

**Other information**

**Comment by jjanedoh** [comment]
Everytime I change document folder it also appears to lose document viewer settings and goes zoomed as well as moving the window around the desktop and resizing it

This thing is unusable
