### ISSUE TITLE
Annotations in PDF cannot be deleted

### ISSUE THREAD

**Issue by rvbhute** [linuxmint/xreader#45]
In Xreader 1.0.8, annotations cannot be deleted from the application. Running the following command in a terminal works; however, it clears _all_ annotations in the PDF.

```
gvfs-set-attribute /path/to/file.pdf metadata::evince::annotations ''
```

This solution was suggested on this AskUbuntu page - http://askubuntu.com/a/249469/80602. While it is for Evince, it obviously worked for Xreader also.

**Comment by JosephMcc** [comment]
Yeah, this really needs to be implemented. It's annoying unless I just figure out how to do it. If there is a way it needs to be much easier.

**Comment by Laurencio** [comment]
+1 for this request

**Comment by mickaelalbertus** [comment]
I  corrected it :) cf #199

**Comment by Laurencio** [comment]
Oh, sorry i hadn't seen it.
My I ask here how can I apply the fix? I guess not. but anyway, glad to hear it has been corrected. Why didn't your fix get into the updates?

**Comment by Piiit** [comment]
@Laurencio @mickaelalbertus  Is it solved? Can we close this issue?

**Comment by mickaelalbertus** [comment]
Yes you can delete annotations by right clicking them and delete action.

Le sam. 16 mai 2020 à 20:33, Peter Moser <notifications@github.com> a
écrit :

**Comment by Piiit** [comment]
Thx
