### ISSUE TITLE
Bug report xreader: Space bar not working

### ISSUE THREAD

**Issue by Scahry** [linuxmint/xreader#457]
Steps to reproduce:
1. Open a document in xreader 2.8.3
2. Hit the space key

Result: Nothing happens
Expectation: The document should scroll down, just like it did in a previous version not so long ago. E.g. it worked on my machine two weeks ago.

As a discussion on IRC revealed, the problem exists not only on Linux Mint, but also on other operating systems with xreader.
In the IRC it also became apparent that the problem did not exist in xreader 2.6.4 (if I recall it correctly).

Is this feature really necessary?
Yes:
 - Many other programs on both Linux and Windows, e.g. Firefox, Chrome, Adobe Reader and man-pages in terminal, support scrolling with the space bar, and I don't want to learn different shortcuts for every program.
 - There is also the "page down"-Key, which does pretty much the same thing. But on my laptop keyboard, there is no actual "page down" key, you would have to press Fn+Arrow down. Space is more comfortable.

Also, it is inconsistent that Shift+Space still works for scrolling up, while Space for scrolling down doesn't, so I conclude that it was not intentional to remove this feature (it would be moronic to remove it intentionally). Please bring this feature back.

**Comment by icarter09** [comment]
@Scahry I put up a PR that should allow you scroll down when the space key is pressed. Let me know if that doesn't fix the issue for you. Thanks.

**Comment by Scahry** [comment]
It doesn't work. When I hit the space button in version xreader-b83cbc22e556827eaf2fede90cb6d06a79d98d9c, still nothing happens. Does it work on your machine?

**Comment by icarter09** [comment]
Xreader v2.8.3
Mint 20.1 64bit

Yes it works on my machine. The focus does need to be on the main view in order for it to work.

**Comment by Scahry** [comment]
I loaded the old xreader version 2.6.2 from github and it still doesnt work so maybe some libaray updated or my OS is busted.

**Comment by Scahry** [comment]
now it does work with the old version... strange
