### ISSUE TITLE
HTML radio buttons (generated by LaTeX) are not functioning correctly

### ISSUE THREAD

**Issue by EnronEvolved** [linuxmint/xreader#460]
```
 * xreader 2.8.3
 * Distribution - Mint 20.1
```

## Issue

I'm attempting to write some pdf forms in LaTeX (using hyperref) that use radio buttons. These radio buttons do not seem to function properly in xreader, as only the first button renders properly: the rest are replaced by what I believe to be slightly distorted apostrophes.

## Steps to Reproduce

I compiled the following LaTeX in TeXStudio, based on an [online example](https://martin-thoma.com/creating-pdf-forms-with-latex/):

```latex
\documentclass[a4paper,12pt]{article}
\usepackage{amssymb} % needed for math
\usepackage{amsmath} % needed for math
\usepackage[utf8]{inputenc} % this is needed for german umlauts
\usepackage[margin=2.5cm]{geometry} %layout

\usepackage{hyperref}  % this is needed for forms and links within the text

\hypersetup{
  pdfauthor   = {Martin Thoma},
  pdfkeywords = {Martin Thoma, example, LaTeX, form},
  pdftitle    = {An example for a LaTeX form}
}

\begin{document}

\title{An example for a LaTeX form}
\author{Martin Thoma}
\date{\today}

\section{An example for a \LaTeX~form}

\begin{Form}[action=mailto:info@example.com, encoding=html, method=post]
\subsection{Some general information:}
\begin{tabbing}
    xxxxxxxxxx: \= \kill  % This is needed for the right tab width
    Name:    \> \TextField[name=name,width=3cm,charsize=12pt]{\mbox{}}
    Prename:    \TextField[name=vor,width=3cm,charsize=12pt]{\mbox{}} \\
    City:    \> \ChoiceMenu[combo, name=city, width=5cm, charsize=12pt, default=Karlsruhe]{\mbox{}}{Chemnitz, Dresden, Leipzig, Berlin, Hamburg, Karlsruhe, München} \\

    Sex:    \> \ChoiceMenu[radio, default=x, name=sex, charsize=14pt]{\mbox{}}{Male=m, Female=f, Non-binary=x}
\end{tabbing}

\subsection{Education:}
\CheckBox[name=highschool, charsize=12pt]{High School}
\CheckBox[name=college, charsize=12pt]{College}
\CheckBox[name=university, charsize=12pt]{University} \\


\Submit{Submit}
\Reset{Clear}
\hfill ~\\
\end{Form}

\end{document}
```

## Expected Behaviour

Correct rendering behaviour (similar to what is observed when the document is read in Firefox).

## Other Information

The rendering problems do not arise from the small modifications that I have made to the source file. The original author of text even notes that the radio buttons are "buggy".

I have attached the pdf output [here](https://github.com/linuxmint/xreader/files/5881111/form.pdf).
.

**Comment by Piiit** [comment]
Same bug in Evince 3.36.7... this might be a poppler issue

Eventually you could extend your bug report to https://gitlab.freedesktop.org/poppler/poppler/-/issues?label_name%5B%5D=forms

**Comment by EnronEvolved** [comment]
Looking over at [their Gitlab issues](https://gitlab.freedesktop.org/poppler/poppler/-/issues?label_name[]=forms), poppler is riddled with long-standing bugs related to forms...

I managed to reproduce the issue in Okular, as well, so it looks like another poppler form rendering bug. I'm not sure about whether this should remain open, if the problem isn't in xreader.
