### ISSUE TITLE
Progress concerning the toolbar?

### ISSUE THREAD

**Issue by scytho** [linuxmint/xreader#466]
```
 * Xreader version (xreader --2.4.4)
 * Distribution - (Mint 19.3)
```

Years ago I read somewhere that the toolbar of xreader is rather empty, because xreader was migrated to GTK3 from GTK2 and there hasn’t been enough time to build the new GUI with GTK3, yet.

As I said, that was years ago. I’ve been waiting really patiently, but I still see no option for editing the toolbar. There are way less icons in the toolbar than Atril/Evince used to have back in the good old times of GTK2. What we are seeing now, is this the final design? Won’t we get to have options, customisability, more GUI toolbar icons?

**Comment by JosephMcc** [comment]
There is some customization but it's only added when it feels like there is an actual reason. There are no plans to bring back the type of editing you could do in the past.

**Comment by scytho** [comment]
What would be an actual reason? Having options isn’t, I guess.

**Comment by scytho** [comment]
That was a serious question. What, for instance, is the reason for not adding buttons that control single and double page view?

**Comment by scytho** [comment]
Sorry for putting it that bluntly, but you make quite an ignorant appearance. Why do you actually think there is no actual reason for editing the toolbar, let alone have more GUI elements in it, editable or not? I’d really like to understand.

**Comment by scytho** [comment]
This is part of why Mate is dead to me. Sorry, but it just sucks. This is unacceptable. There is hardly any reason left for picking Mate over something like any version of Windows, UI-wise. It’s a shame what has become of Gnome 2’s legacy.
