### ISSUE TITLE
ENTER does not work in Presentation Mode

### ISSUE THREAD

**Issue by mcp292** [linuxmint/xreader#469]
```
xreader 2.8.3
Arch
```

**Issue**
`ENTER` does not work in Presentation Mode and `SPC` does not work in normal viewing. This is very confusing and unnecessary. Why not support both in both contexts? Why change default behavior when the user is presenting?

**Comment by icarter09** [comment]
xreader 2.8.3
Mint 20.1

Both `ENTER` and `SPC` are working in normal viewing to go to the next page. 

I do see the issue that `Enter` is not working in Presentation Mode.

**Comment by kolayne** [comment]
This should be closed (#475), shouldn't it?
