### ISSUE TITLE
Build failure on linking webkitgtk library- undefined reference to _gst_debug_min

### ISSUE THREAD

**Issue by doniaalwin** [linuxmint/xreader#470]
```
 * Linux version (linux --version)
 * Distribution - (Ubuntu 20.04, etc...)
```

**Issue**

Build fails because of following error
usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libwebkit2gtk-4.0.so: undefined reference to `GST_CAT_DEFAULT'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libwebkit2gtk-4.0.so: undefined reference to `_gst_debug_min'

Expected behaviour
Build successful.

Other information
 Gstreamer 1.18.3 - built from scratch
 gtk-webkit - installed by apt get

**Comment by leigh123linux** [comment]
There is a gstreamer1 headers mismatch.
