### ISSUE TITLE
xreader segfaults trying to do a find in an epub document

### ISSUE THREAD

**Issue by polaris6262** [linuxmint/xreader#495]
```
 * Xreader version 3.0.0 and 3.0.1
 * Distribution - Arch
```

**Issue**
Opening the epub document works normally, but opening the find window with CTRL-F and entering just one character causes the application to crash on a signal 11 (segfault).

**Steps to reproduce**
Open epub document, select edit -> find, start to type withing the find windows at the bottom of the document; within a second the application crashes.

**Expected behaviour**
Find allows a string to be entered and located withing the document text.

**Other information**
This is from the system log:

[  323.268978] xreader[2274]: segfault at 0 ip 00007f9b7efb373c sp 00007ffea58cce10 error 4 in libxreaderview.so.3.0.0[7f9b7efac000+28000]
[  323.268990] Code: 1f 80 00 00 00 00 8b 4b 68 48 8b 53 60 4c 89 ee 4c 89 f7 ff 15 bd 31 03 00 49 89 c4 e9 30 ff ff ff 0f 1f 44 00 00 48 8b 43 58 <4c> 8b 27 8b 34 88 31 c0 85 f6 0f 95 c0 89 43 6c e9 59 ff ff ff 66

It should be mentioned that downgrading to xreader 2.8.3 fixes the problem.

**Comment by AKorezin** [comment]
Bug was introduced by #467.

For arch you can use following `PKGBUILD`. I've added `source` and rollback the patch in `prepare()`.
Nevertheless check diff with the official `PKGBUILD`.
```sh
# Maintainer: Bruno Pagani <archange@archlinux.org>
# Contributor: Eli Schwartz <eschwartz@archlinux.org>
# Contributor: Nate Simon <aurpkg (at natesimon.net)>

pkgname=xreader
pkgver=3.3.0
pkgrel=1
pkgdesc="Document viewer for files like PDF and Postscript. X-Apps Project."
arch=(x86_64)
url="https://github.com/linuxmint/${pkgname}"
license=(GPL)
groups=(x-apps)
depends=(poppler-glib webkit2gtk xapps)
optdepends=('djvulibre: support for djvu files'
            'libgxps: support for xps files'
            'libspectre: support for dvi and ps files'
            'mathjax2: support for math in epub files'
            'texlive-bin: support for dvi files')
makedepends=(meson samurai intltool itstool gobject-introspection djvulibre
             libgxps libspectre texlive-bin)
source=("${url}/archive/${pkgver}/${pkgname}-${pkgver}.tar.gz"
        "epub_search_crash.patch::${url}/commit/4f766a7.diff")
sha256sums=('cd347ce2c4d655adc296c25d475250a688921af6a54581bcf10e279276197e54'
            '5af092bba02242210a9a69eb657a33120c52ca30ff631ff4399486e6d99035cc')
b2sums=('4194a002eba3a903db574e66478cbd5d551e37e99f278d0e0fd3d8981c33ee7fad729a47554c54f098b5fba9bdf93245f876a15e6f13441ac38d0e54e14dc77c'
        'ea93b459654e4941e1c9ad29cff92ff6d75b9889f1e3b29ad6d70a0f78c7e48339ad5e34760c58f9546fe875f1f5479cdf37bb6f110ab04ef7c5a6c590d9cc48')

prepare() {
  cd "${pkgname}-${pkgver}"
  patch -Np1 -R < "${srcdir}/epub_search_crash.patch"
}

build() {
  arch-meson ${pkgname}-${pkgver} build \
    --libexecdir=lib/${pkgname} \
    -Dmathjax-directory=/usr/share/mathjax2 \
    -Dcomics=true \
    -Ddjvu=true \
    -Ddvi=true \
    -Dt1lib=true \
    -Dpixbuf=true \
    -Dhelp_files=true \
    -Dintrospection=true
  samu -C build
}

package(){
  DESTDIR="${pkgdir}" samu -C build install
}
```
