### ISSUE TITLE
Copied text from PDF file is completely wrong

### ISSUE THREAD

**Issue by Atalanttore** [linuxmint/xreader#500]
```
 * Xreader version: 3.0.2
 * Distribution: Linux Mint 20.2
```

**Issue**
The text copied from a PDF file is completely wrong.

**Steps to reproduce**

1. Open this [PDF file](http://www.dglr.de/publikationen/2016/420025.pdf) in Xreader
2. Select any text
3. Copy the selected text
4. Paste the text into any editor of your choice

**Expected behaviour**
 The pasted text should be the same as the copied text, but it is completely different.

**Comment by AndreiMiculita** [comment]
Doubt this is an xreader issue, it also happens in Firefox.

**Comment by mtwebster** [comment]
I think this is just a bad pdf file.

Same result in chromium, firefox, xreader and evince.
