### ISSUE TITLE
find on epub file causes crash - tested on Xreader 3.0.2

### ISSUE THREAD

**Issue by artofit** [linuxmint/xreader#503]
```
 * Xreader 3.0.2
 * Manjaro XFCE 21.1.3
```

**Issue**
Crash Xreader

**Steps to reproduce**
0. take attached file and rename it as an epub file (github upload does not support epub extension)
1. Open attached ePub file with Xreader
2. type CTRL+F to open the find command
3. type (in find) a key, for instance a, just wait a 2 secs and Xreader closes

**Other information**
Console output:
`xreader

(xreader:42626): Gtk-CRITICAL **: 04:45:53.137: _gtk_css_image_get_concrete_size: assertion 'default_width > 0' failed

(xreader:42626): Gtk-CRITICAL **: 04:45:53.137: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed

(xreader:42626): Gtk-CRITICAL **: 04:45:53.137: _gtk_css_image_get_concrete_size: assertion 'default_width > 0' failed

(xreader:42626): Gtk-CRITICAL **: 04:45:53.137: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed

(xreader:42626): Gtk-CRITICAL **: 04:45:55.686: _gtk_css_image_get_concrete_size: assertion 'default_width > 0' failed

(xreader:42626): Gtk-CRITICAL **: 04:45:55.686: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed

(xreader:42626): Gtk-CRITICAL **: 04:45:55.686: _gtk_css_image_get_concrete_size: assertion 'default_width > 0' failed

(xreader:42626): Gtk-CRITICAL **: 04:45:55.686: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed
Erreur de segmentation (core dumped)

`
[xreader302crashrenamefileasepub.zip](https://github.com/linuxmint/xreader/files/7199875/xreader302crashrenamefileasepub.zip)

**Comment by tstivers1990** [comment]
Experience this as well, although it says this when crashing, in my case. I don't see the error messages in the original post.

```bash
zsh: segmentation fault (core dumped)  xreader
```

This file specifically causes crash on find: https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/epub/virtual_machine_management_guide/red_hat_virtualization-4.4-virtual_machine_management_guide-en-us.epub (if you don't have an account, you can create a developer account for access)

**Comment by karakartala** [comment]
Xreader 3.2.2 has the same issue.

**Comment by mtwebster** [comment]
Fixed:
https://github.com/linuxmint/xreader/commit/9c6022dcba442579568319a272ab9aea2310d365
