### ISSUE TITLE
Attachments cannot be seen / opened / saved

### ISSUE THREAD

**Issue by RealMabuse** [linuxmint/xreader#51]
I have got PDF documents containing attachments.

Opening those documents in Xreader will not give me any access to the attachments, I even cannot see there are attachments.

Xreader should be able to show or at least to save attachments to disk.

**Comment by Piiit** [comment]
@RealMabuse I cannot reproduce this issue. Could you please upload a test-file...

**Comment by RealMabuse** [comment]
@Piiit just tried to create a pdf with attachments and encrypted it with pdftk.
What can I say... It worked fine.

I cannot upload the existing pdf documents which not working, because they contain certain personal data, I'm sorry. The document containg attachments is encrypted, contains multiple attachments and Xreader has the Attachment menu grayed out, the document works fine with Acrobat Reader on Windows.

I will try to get some uploadable document samples and will ask for the software used to produce the documents, but it will take some days...

**Comment by RealMabuse** [comment]
I spoke with the creator. They told me they know about the thing their documents can be viewed exclusively with Acrobat Reader. Their software seem not to produce compliant pdf.
I'll bet their their software will cost about thousands of euros instead of using tools like pdftk...
Sorry, I will close this issue.
