### ISSUE TITLE
Window is only apparently maximized

### ISSUE THREAD

**Issue by palimmo** [linuxmint/xreader#516]
```
 * Xreader version: 3.0.2
 * Distribution: Mint 20.2
```

**Issue**
Window is only apparently maximized. 
If you go with the cursor exactly in the corner, you won't be able to close the windows, but to adjust its size. To close it you have actually to move back 1 mm to the "x" button.

**Steps to reproduce**

1. Launch Nemo.

2. Open a .pdf by double click it.

3. Once opened, if the window is not maximized, click on the maximize icon (beside the "x" button) to maximized the window.

4. Once maximized, close the document (with the "x").

5. In Nemo open another .pdf document.

6. Result: the window of the .pdf document seems completely maximized, but it is not! If you go eactly in the corner, the cursor give you the option to adjust the window size instead of the option to close it.
To close it you have actually to move back 1 mm to the "x" button.

Oddity:
If you reopen the same document after you have manually maximized it, it will be correctly displayed.
On the other hands with new documents you will mostly get windows that are "almost" correctly maximized.

Affected apps:
apparently only xreader.

**Expected behaviour**
If a window is correctly maximized, clicking exactly in the top-right corner should give you the certainty to quickly close the window.

**Other information**
Cinnamon version 5.0.7

**Comment by graue70** [comment]
I have the same problem with xreader and I also have it with mintUpdate 5.7.8. It always opens almost maximized.

**Comment by Jeronimo17** [comment]
In Linux Mint 20.3 Una I think it's the same as described by the OP I have to maximize the window in new PDFs, then the same ones seem to stay saved settings, it's quite annoying.

Xreader 3.2.2

![NoMaximizado](https://user-images.githubusercontent.com/4985763/178789659-03eab181-893c-4315-a5d7-b6582c80776f.png)

**Comment by Jeronimo17** [comment]
Any flags to launch it maximized?

**Comment by trondsg** [comment]
I also have this problem. The window size seems to be saved on a per-file basis, instead of for the application. Further, it does not remember maximized state.

**Comment by tfpf** [comment]
I hacked around and came up with the following.

```diff
diff --git a/shell/ev-window.c b/shell/ev-window.c
index e4b6b86..6b271bb 100644
--- a/shell/ev-window.c
+++ b/shell/ev-window.c
@@ -1094,6 +1094,9 @@ ev_window_init_metadata_with_default_values (EvWindow *window)
     if (!ev_metadata_has_key (metadata, "fullscreen")) {
         ev_metadata_set_boolean (metadata, "fullscreen", g_settings_get_boolean (settings, "fullscreen"));
     }
+    if (!ev_metadata_has_key (metadata, "window_maximized")) {
+        ev_metadata_set_boolean (metadata, "window_maximized", g_settings_get_boolean (settings, "window-maximized"));
+    }
 }
 
 static void
@@ -4485,6 +4488,8 @@ ev_window_cmd_edit_save_settings (GtkAction *action,
             ev_document_model_get_dual_page_odd_pages_left (model));
     g_settings_set_boolean (settings, "fullscreen",
             ev_document_model_get_fullscreen (model));
+    g_settings_set_boolean (settings, "window-maximized",
+            gtk_window_is_maximized (GTK_WINDOW (ev_window)));
     g_settings_set_boolean (settings, "inverted-colors",
             ev_document_model_get_inverted_colors (model));
     sizing_mode = ev_document_model_get_sizing_mode (model);
```

However, there is no setting to record the window state.

```
(xreader:4035): GLib-GIO-ERROR **: 12:01:44.902: Settings schema 'org.x.reader.default' does not contain a key named 'window-maximized'
Trace/breakpoint trap (core dumped)
```

So, I tried:

```diff
diff --git a/shell/ev-window.c b/shell/ev-window.c
index e4b6b86..161b9d8 100644
--- a/shell/ev-window.c
+++ b/shell/ev-window.c
@@ -1094,6 +1094,9 @@ ev_window_init_metadata_with_default_values (EvWindow *window)
     if (!ev_metadata_has_key (metadata, "fullscreen")) {
         ev_metadata_set_boolean (metadata, "fullscreen", g_settings_get_boolean (settings, "fullscreen"));
     }
+    if (!ev_metadata_has_key (metadata, "window_maximized")) {
+        ev_metadata_set_boolean (metadata, "window_maximized", TRUE);
+    }
 }
 
 static void
```

and it worked—every new PDF file opened in a maximised window. (If the file had been opened previously, it remembered that state and opened the file in a window in the same state.)

The first fix requires adding a new key to the settings schema (which I don't know how to do, and I imagine is quite complicated); the second is rather straightforward, but displays every new PDF file in a maximised window (which shouldn't inconvenience any user). Personally, I'd like to go the second, but would like to hear suggestions.
