### ISSUE TITLE
yellow color not visible in a claender of 2022, while it is ok with firefox or other explorers, how can I send this page to examin

### ISSUE THREAD

**Issue by arif-raza** [linuxmint/xreader#524]
```
 * Xreader version (xreader --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
Use the template next time and provide the required info.

**Comment by arif-raza** [comment]
thank, attaching a single page of calendar for garbage, on t5th Jan. is for
paper/carton in yellow color, which
is not visible with the document xreader or evince , but all with all nwt
wzploreres

Il giorno lun 17 gen 2022 alle ore 11:38 Leigh Scott <
***@***.***> ha scritto:
