### ISSUE TITLE
Menu bar, after hidden not recoverable

### ISSUE THREAD

**Issue by vagonbar** [linuxmint/xreader#525]
```
 * Xreader version (xreader --3.2.2)
 * Distribution - Mint 20.3 Una
```

**Menu bar, after hidden not recoverable**

**Steps to reproduce**
After hiding menu bar with Menu / View / Hide menu bar (or similar, my version is in Spanish),
  - there is no option to make it visible again.
  - combination keys Alt- do not work any more.

Solution:
```   $ gsettings set org.x.reader show-menubar true ```

**Expected behaviour**
  The former is a non end-user solution; keeping alive Alt- keys for menu bar functions would solve the issue, and also allow for use of menu bar functions; maybe also assign a specific key combination to make menu bar visible, as with tool bar Shift-Ctrl-T, perhaps Shift-Ctrl-M.
  Thank you.

**Other information**

**Comment by cmcl** [comment]
I am running the same version of xreader under Mint 20.3 Una, yet pressing Alt restores the menubar for me. Can you confirm if this issue still exists?

**Comment by vagonbar** [comment]
Ok, pressing Alt key restores menubar. Perhaps adding this Alt key behavior to the list of shortcut keys might be of help.
Thank you.
