### ISSUE TITLE
remove bookmark

### ISSUE THREAD

**Issue by Alexey1307** [linuxmint/xreader#539]
```
 * Xreader version (xreader --version)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
```

**Issue**

how to delete a bookmark?

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by highsinuhe** [comment]
Open the side panel and pull down the multiple options button and select bookmarks, from there you can delete them, they cannot be deleted from the menu bar, only from the side panel where the index options, bookmarks, etc. appear.

**Comment by Alexey1307** [comment]
> Open the side panel and pull down the multiple options button and select bookmarks, from there you can delete them, they cannot be deleted from the menu bar, only from the side panel where the index options, bookmarks, etc. appear.

Thanks a lot! it works!
