### ISSUE TITLE
xreader does not open the attached pdf

### ISSUE THREAD

**Issue by tevorbl** [linuxmint/xreader#558]
```
xreader 3.3.0
opensuse 15.4 
```

**Issue**

The file fails to open.   There is no crash, just a blank display area.  
No diagnostics reported.   
xreader can be can be closed without problems.
also occurs with previous version (xreader-2.8.3-bp154.1.155.x86_64)

**Steps to reproduce**

open the file, eg on the command line, type:

xreader air.pdf

**Expected behaviour**

the file contents should be displayed.
expected behavior occurs for okular, evince & qpdfview 

**Other information**

[air.pdf](https://github.com/linuxmint/xreader/files/8992013/air.pdf)

**Comment by danielp96** [comment]
I can open it with xreader 3.2.2 on mint 20.3
![image](https://user-images.githubusercontent.com/17953536/180265516-22e85345-19ab-42ed-a76c-9b046e077b7f.png)

**Comment by mtwebster** [comment]
Works fine in 3.4.2 (latest).

Any chance you can upgrade to that one?

**Comment by tevorbl** [comment]
3.4.2 not yet available for me.  I went back a version, and that works fine for me.
I'll upgrade to 3.4.2 when becomes available.

as far as I'm concerned, you can close this issue.
