### ISSUE TITLE
Letters D, F and W not accepted when editing PDF file with form fields.

### ISSUE THREAD

**Issue by jbergengh** [linuxmint/xreader#563]
```
 * Xreader version 3.4.4
 * Distribution - LMDE5
```

**Issue**
After opening a PDF with editable forms, I cannot type the letters D, F or W in any of the editable fields.

**Steps to reproduce**
Open the attached PDF file with Xreader version 3.4.4
Click on the "Full Name" field and attempt to type in a name that contains the letters D, F or W.
The letters D, F and W are not accepted because they are shortcut keys.

**Expected behaviour**
D, F and W should be accepted.  I suggest these single character shortcut keys be changed to Ctrl+ or Fn keys instead.

[2019_BSA_Medical_Form_AB.pdf](https://github.com/linuxmint/xreader/files/9332644/2019_BSA_Medical_Form_AB.pdf)

**Comment by SethosII** [comment]
I also have this issue but I noticed it when trying to search. If you enter any letter with a shortcut (e. g. `d` or `f`) in the search field it executes these command and the letter is not written.

```
Linux Mint 21
xreader 3.4.4
```

**Comment by jbergengh** [comment]
...and when renaming Bookmarks.

**Comment by jbergengh** [comment]
More info:  I used Timeshift to restore my system back to before the latest update.  Doing so restored Xreader from version 3.4.4 back to version 3.4.3.
Version 3.4.3 accepts characters D, F and W as it should, both when filling out PDF forms and when searching.

Next, Mintupdate required an update, which I did.

After Mintupdate updated, additional updates were available for cinnamon, mintreport, sticky and xreader.

I accepted all of those updates except Xreader.  I kept version 3.4.3 and refused the updated version 3.4.4

After all updates were installed, (except Xreader) Xreader version 3.4.3 is working as it should.

The issue with D, F, and W keys appears to have been introduced in Xreader version 3.4.4.

**Comment by pilatomic** [comment]
Can confirm, same issue on 3.4.4, cannot enter a 'D', 'F' nor 'W' in the search fields.

**Comment by photong** [comment]
A rough workaround is to use D, F, and W (capital letters) with case insensitive search.

**Comment by ovari** [comment]
When in Search/Find, moving through the characters works with the `left arrow` and `right arrow`; however, moving through the words with `Ctrl`+`left arrow` and `Ctrl`+`right arrow` does not work as it rotates the preview.

Has this been fixed? If not, does a new issue need to be created?

Thank you

**Comment by rccsw** [comment]
I am experiencing this as well in fillable PDF - unable to use d f w in fillable field

**Comment by pilatomic** [comment]
Hello,
Just got the Xreader 3.4.5 update, can confirm issue of not being able to search for letters D, F and W is now fixed for me in version.
Thank you !

**Comment by rccsw** [comment]
Looks like it's working now, thank you for the quick response and update.
Im new to linux and communicating on github. I was trying to follow the
Odin Project and freecodecamp. Not a huge passion there though so I
don't know if it will go far. Coding seems really unappreciated, thankless,
and difficult. I do appreciate the many apps available for linux that are
allowing me to use it everyday. I really just am tired of Microsoft, but
it's the most compatible software. Thanks again

**Comment by rccsw** [comment]
Working for me now, thanks

**Comment by rccsw** [comment]
Appears to be working for me now with update
