### ISSUE TITLE
Letter keys that are also shortcuts can't be entered in searches

### ISSUE THREAD

**Issue by ooglyhLL** [linuxmint/xreader#565]
```
 * Xreader version (3.4.4)
 * Distribution - (Mint 21)
```

**Issue**

Letter keys that are also shortcuts (e.g. ‘d’, ‘f’) can't be entered in searches.

**Steps to reproduce**

1. open PDF document
2. Ctrl-f (Find)
3. Start typing string containing the letter ‘d’.

**Expected behaviour**

The letter ‘d’ appears in search string. Instead the document view toggles between dual and single page layout.

**Other information**

**Comment by ovari** [comment]
`w` can not be typed in Search and toggles `Reader View`.

**Comment by ovari** [comment]
When in Search/Find, moving through the characters works with the `left arrow` and `right arrow`; however, moving through the words with `Ctrl`+`left arrow` and `Ctrl`+`right arrow` does not work as it rotates the preview.

**Comment by mtwebster** [comment]
duplicate (and fixed): https://github.com/linuxmint/xreader/issues/563
