### ISSUE TITLE
Unfortunate default shortcuts

### ISSUE THREAD

**Issue by ZuseZ4** [linuxmint/xreader#566]
```
 * Default (3.4.4)
 * Linux Mint 21 Cinnamon  
```

**Issue**
Hi everyone, I recently switched from Ubuntu to Linux Mint, which came with xreader pre-installed.
I tried to search a few things in a pdf and quickly noticed that I am unable to search any words containing either
a d or an f, since those seem to be shortcuts in xreader. 
This surprised me, since I assume that most people will rather use the search functionality then
those specific shortcuts. Also, I haven't been able to easily deactivate those shortcuts, 
maybe it would help to either offer a nicer gui solution for changing those or use some slightly more complex shortcuts,
s.t. that don't interfere with the search usage?
Feel free to close this issue if you feel that the default settings are more convenient and that I have a strange usage pattern.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by Piiit** [comment]
Duplicate and already fixed... just wait for the new release :-D

#563 #565
