### ISSUE TITLE
Key-Press Issue

### ISSUE THREAD

**Issue by OdinVex** [linuxmint/xreader#567]
```
 * Xreader version 3.4.4
```

**Issue**
Trying to type in any string with the letter 'd' toggles dual pages, despite focus being in the textbox for CTRL+F. Too big a headache to fill this out more.

**Comment by mtwebster** [comment]
Update to 3.4.5

**Comment by OdinVex** [comment]
Was it fixed in 3.4.5? I would have thought Mint would be running the latest release, considering it is a Mint project..

**Comment by mtwebster** [comment]
Ah sorry the build server is having trouble with it, so it's not in the repositories yet.

It's fairly simple to build on Mint if you want to try:

```
apt install git
git clone https://github.com/linuxmint/xreader.git
cd xreader
apt build-dep xreader
dpkg-buildpackage

cd ..
sudo dpkg -i *.deb
```
or the Mint daily ppa:
https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds
Though I would recommend only updating xreader from it, then disabling.

**Comment by wujastyk** [comment]
Thank you @mtwebster!   The ppa worked perfectly.  I updated just xreader and disabled the ppa again, as you suggested.

**Comment by OdinVex** [comment]
Confirming fixed.

**Comment by wujastyk** [comment]
Confirmed here.
