### ISSUE TITLE
Open Plain Text File

### ISSUE THREAD

**Issue by jfcaron3** [linuxmint/xreader#575]
```
 * Xreader version 3.4.5
 * Distribution - Linux Mint 21 MATE
```

**Issue**
I try to open a plain text file.  

**Steps to reproduce**
Use File->Open menu, change file filter from "All Documents" to "All Files".  Select a plain text file.  I get the error: 
"Unable to open document
File type plain text document (text/plain) is not supported"

**Expected behaviour**
Open the file and display it.

**Other information**
I was looking for a "GUI Pager" for plain text files that wasn't an entire text editor.  E.g. for reading READMEs and other files.  I feel like some plain text files can be legitimately interpreted as "documents" so it makes sense for xreader to support them.

**Comment by leigh123linux** [comment]
xreader is for reading pdf only, use xed for text.

**Comment by jfcaron3** [comment]
I don't always want to use a text editor to view files.  The edit functions get in the way of just *reading* a thing.  

Also "Xreader is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript."
Also it looks like with backends it can read TIFF, DjVu, CBR, DVI, and other formats. 

Should we remove the TIFF functionality and tell people to just use GIMP?

Anyways, no big deal.  It was just weird seeing a "generic document viewer" not support plain text.
