### ISSUE TITLE
Barcode displayed as black rectangle

### ISSUE THREAD

**Issue by ygramoel** [linuxmint/xreader#577]
```
 * Xreader version 3.2.2
 * Distribution - Mint 20.3 Cinnamon 5.2.7
```

**Issue**

This one page document contains a barcode. Xreader displays it as an almost completely black rectangle, which cannot be scanned by any barcode scanner.  It is also printed as a black rectangle. Other PDF viewers, such as Foxit Reader, display it correctly.
[unreadable_barcode.pdf](https://github.com/linuxmint/xreader/files/9839346/unreadable_barcode.pdf)

**Steps to reproduce**

Open the document linked above.  It looks like this image:

![unreadable_barcode](https://user-images.githubusercontent.com/24917266/197205758-bc98ce16-9677-49ea-b005-acb707c22e65.png)

**Expected behaviour**

It should look like this:  
![readable_barcode](https://user-images.githubusercontent.com/24917266/197206041-45eceae9-8c32-45ef-a3ae-402aa350aecf.png)

**Other information**

**Comment by leigh123linux** [comment]
Chromium is the same so it's a bad pdf file.

![image](https://user-images.githubusercontent.com/1299302/197221840-3a019ed5-1dd4-4f58-8c13-210dc9fc2331.png)

**Comment by ygramoel** [comment]
> Chromium is the same so it's a bad pdf file.
> 
> ![image](https://user-images.githubusercontent.com/1299302/197221840-3a019ed5-1dd4-4f58-8c13-210dc9fc2331.png)

Hmmm, you are right about the pdf that I uploaded.  That was just the second page out of a three page document, and I "printed" that second page to a file using Xreader;  so it is indeed a bad pdf,  generated by Xreader.

You can find the original file at [https://sikando.com/unreadable_barcode.pdf](https://sikando.com/unreadable_barcode.pdf).  This file displays correctly in Chromium (and Firefox and several PDF readers that I tried),  but not in Xreader.



> ```
>  * Xreader version 3.2.2
>  * Distribution - Mint 20.3 Cinnamon 5.2.7
> ```
> 
> **Issue**
> 
> This one page document contains a barcode. Xreader displays it as an almost completely black rectangle, which cannot be scanned by any barcode scanner. It is also printed as a black rectangle. Other PDF viewers, such as Foxit Reader, display it correctly. [unreadable_barcode.pdf](https://github.com/linuxmint/xreader/files/9839346/unreadable_barcode.pdf)
> 
> **Steps to reproduce**
> 
> Open the document linked above. It looks like this image:
> 
> ![unreadable_barcode](https://user-images.githubusercontent.com/24917266/197205758-bc98ce16-9677-49ea-b005-acb707c22e65.png)
> 
> **Expected behaviour**
> 
> It should look like this: ![readable_barcode](https://user-images.githubusercontent.com/24917266/197206041-45eceae9-8c32-45ef-a3ae-402aa350aecf.png)
> 
> **Other information**
