### ISSUE TITLE
Document how to build and run

### ISSUE THREAD

**Issue by fernandoacorreia** [linuxmint/xreader#59]
It would help to have a document explaining how to build xreader e.g. to compile and run the latest `master` version.

On Linux Mint 18, I started by trying to run the "standard" `./configure` and `autoreconf` -- no luck.

Then I browsed the files and found `autogen.sh`.

On each run it would break because of a missing package. These are the packages that I had to install:
- autoconf, autotools-dev, automake (not sure if required, this was when trying to run `autoreconf`)
- mate-common
- yelp-tools
- glib-gettext
- libglib2.0-dev
- build-essential
- libgtk-3-dev
- libgail-3-dev
- libgtk2.0-dev
- libxml++2.6-dev
- libsecret-1-dev
- libcaja-extension-dev
- libnemo-extension-dev
- libnemo-extension-dev
- libpoppler-glib-dev

To get to this point took me 15 attempts.

After that I ran `make`, but when it finished compiling it wasn't clear where the binary was.
I found `shell/xreader` but that wasn't it.

At that point I gave up -- it's just too much detective work to try to test a PR.

So I think that if you add some documentation on how to build and run, it would help more people get involved.

What would be really great would be a Docker image for building, so that people didn't have to mess with installing dependencies on their hosts.

**Comment by NikoKrause** [comment]
@fernandoacorreia 
Have you Trier `sudo checkinstall` after `make`?

**Comment by fernandoacorreia** [comment]
```
$ sudo checkinstall
[sudo] password for fernando: 
sudo: checkinstall: command not found

$ sudo apt-get install checkinstall

$ sudo checkinstall
```

That installed a lot of libraries (not exactly what I was expecting, but OK), asked me some unexpected questions that I really didn't know how to answer, and finally failed.

```
Some of the files created by the installation are inside the home directory: /home

You probably don't want them to be included in the package.
Do you want me to list them?  [n]: 
Should I exclude them from the package? (Saying yes is a good idea)  [n]: yes

Some of the files created by the installation are inside the build
directory: /home/fernando/scratch/xreader

You probably don't want them to be included in the package,
especially if they are inside your home directory.
Do you want me to list them?  [n]: y
Should I exclude them from the package? (Saying yes is a good idea)  [y]: yes

Copying files to the temporary directory...OK

Stripping ELF binaries and libraries...OK

Compressing man pages...OK

Building file list...OK

Building Debian package... FAILED!

*** Failed to build the package
```

Log was:

```
dpkg-deb: error: parsing file '/var/tmp/tmp.xfIsSnKMKH/package/DEBIAN/control' near line 10 package 'xreader':
 empty value for version
```

To be clear, this issue is not about debugging how to build it on my machine, but about providing some build instructions, e.g. for building and running it on a default Linux Mint 18 machine.

**Comment by voxspox** [comment]
On debian based distributions everything to build the debian way with `debuild` is already prepared in the `debian` folder.

Check if you have installed all build dependencies with `dpkg-checkbuilddeps`. Install missing packages with your preferred tool p.ex. `apt-get`. Finally build the package with `debuild -us -uc -b`.

**Comment by Piiit** [comment]
Not a duplicate, but belongs to #16

**Comment by Piiit** [comment]
@fernandoacorreia Hi, I wrote a new README... any feedback welcome. See #69
