### ISSUE TITLE
process is ended when saving the annotated pdf

### ISSUE THREAD

**Issue by LeonardoRez** [linuxmint/xreader#609]
```
 xreader 3.8.2 
 Archlinux 
```

When saving an annotated pdf (save a copy -> Ctrl + s), the program closes. I'm not sure if this is a feature or a bug, but I usually save the annotated version when reading a paper, mainly to prevent a loss due to crashing. Reopening the editor every time is kind of annoying. 

(this is my first issue on this project. Let me know if there is some information missing. Thanks in advance.)

**Comment by tyagi-ankit** [comment]
I don't think it's resolved. Xreader still closes automatically after save a copy -> replace. This bug is introduced in mint 21.2. It was not there in mint 21.1.

https://github.com/linuxmint/xreader/assets/25789626/67c23fe5-e3fc-47b3-8045-fec2a2e24293

**Comment by mtwebster** [comment]
The program is fixed, we just haven't done an update yet containing that fix.

**Comment by tyagi-ankit** [comment]
Thanks a lot
