### ISSUE TITLE
Attempting to build the latest release (3.8.2) on both Debian Testing (Trixie) & Debian Unstable (Sid) with the build instructions on INSTALL.md always results in a failure to compile

### ISSUE THREAD

**Issue by blade764** [linuxmint/xreader#621]
### Distribution

Debian Unstable/Sid

### Package version

3.8.2

### Frequency

Always

### Bug description

This is apparently already fixed in a commit made after 3.8.2 was released (Fix building with meson 1.2.), but since that fix isn't in 3.8.2, it continues to fail compilation.

I don't want to use the xreader package from the Debian repos because I want to run a custom build of xreader with specific source code edits that I do to make the program more usable for myself.

I don't know if this project has a specific release schedule, but wouldn't putting out a new release allow the existing build instructions on INSTALL.md to work again?

### Steps to reproduce

Copy pasted the commands from the "Option 1" section at https://github.com/linuxmint/xreader/blob/master/INSTALL.md
everything before "dpkg-buildpackage" works perfectly fine with no errors.
running dpkg-buildpackage results in the meson build error.

### Expected behavior

The program should compile successfully without errors.

**Comment by leigh123linux** [comment]
You will need to patch until the next release.

https://github.com/linuxmint/xreader/commit/06b18a884c8cf3257ea1f053a82784da078999ed
