### ISSUE TITLE
Webkit upgrade makes Xreader 3.8.2 unable to display epub output

### ISSUE THREAD

**Issue by polaris6262** [linuxmint/xreader#622]
### Distribution

Arch Linux Cinnamon 5.8.4 desktop

### Package version

3.8.2

### Frequency

Always

### Bug description

**After a webkit upgrade**:

webkit2gtk (2.40.5-2 => 2.42.0-1)
webkit2gtk-4.1 (2.40.5-2 => 2.42.0-1)
webkitgtk-6.0 (2.40.5-2 => 2.42.0-1)

xreader no longer displays any text. The screen is a large grey area. Document opens fine and the chapter list is as expected, but no text. Even a find works and reports text found, but on a blank screen.

**Downgrading webkit immediately fixes the problem**:

downgrading package webkit2gtk (2.42.0-1 => 2.40.5-2)
downgrading package webkit2gtk-4.1 (2.42.0-1 => 2.40.5-2)
downgrading package webkitgtk-6.0 (2.42.0-1 => 2.40.5-2)

### Steps to reproduce

Simply open an epub file. As previously mentioned, this works fine, including the proper table of contents. This appears to be strictly a display problem, which makes sense as it seems to be related to a new webkit version.

### Expected behavior

The epub text should be displayed properly. This is restored simply by downgrading webkit.

**Comment by leigh123linux** [comment]
The issue doesn't reproduce here, try reporting the issue to archlinux.

![image](https://github.com/linuxmint/xreader/assets/1299302/29c61ef6-dbe5-45d0-ad74-927072703a2d)
