### ISSUE TITLE
Adapt highlighting text for inverted PDFs

### ISSUE THREAD

**Issue by elDan101** [linuxmint/xreader#64]
This is a feature request:
I like to read PDFs in dark, so I often use the "invert colours" function. 

However, when I highlight something in the PDF with inverted colours mode. I can barely see what is actually highlighted. I suppose the inverted colours is usually enabled when there is white background. So I suggest to make the highlight in the inverted mode in a white to light grey colour. 

Example, first without inverted colours, second with inverted colours. Both time the same text is highlighted:

![screenshot from 2016-11-03 15-03-53](https://cloud.githubusercontent.com/assets/8281969/19968955/ff9d804a-a1d6-11e6-8a53-724e9427e4f1.png)
![screenshot from 2016-11-03 15-04-08](https://cloud.githubusercontent.com/assets/8281969/19968962/04f14a18-a1d7-11e6-908e-dc3151604bf5.png)

**Comment by Piiit** [comment]
@elDan101 What theme do you use? I cannot reproduce your issue with mint-y... It seems that you have black background as default selection color... is that right also in other apps?

**Comment by elDan101** [comment]
> What theme do you use?
Mint-Y-Dark

Actually this issue somehow sorted out itself on my computer. It now highlights in a grey-ish color, which is good. I cannot reproduce it myself, so I close this.
