### ISSUE TITLE
xreader.desktop MimeType error

### ISSUE THREAD

**Issue by 0xAlMo3geZ** [linuxmint/xreader#654]
### Distribution

Mint 21.1

### Package version

3.6.6

### Frequency

Always

### Bug description

in /usr/share/applications/xreader.desktop after updating to the latest version provided in apt there is an error in:

MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;application/x-xzpdf;application/postscript;application/x-bzpostscript;application/x-gzpostscript;image/x-eps;image/x-bzeps;image/x-gzeps;application/x-dvi;application/x-bzdvi;application/x-gzdvi;image/vnd.djvu;image/vnd.djvu+multipage;image/tiff;application/vnd.comicbook-rar;application/vnd.comicbook+zip;application/x-cb7;application/x-cbr;application/x-cbt;application/x-cbz;application/x-ext-cb7;application/x-ext-cbr;application/x-ext-cbt;application/x-ext-cbzapplication/oxps;application/vnd.ms-xpsdocument;application/epub+zip;

{{ x-ext-cbzapplication }}

### Steps to reproduce

it should be x-ext-cbz;application

### Expected behavior

no errors after using dpkg to install a package

**Comment by mtwebster** [comment]
This was already fixed:
https://github.com/linuxmint/xreader/commit/495835ec8403eddd85f05c836cb04b2b3de34a7f

You need to use xreader > 4.0 - you'd need to upgrade to Mint 21.3 or you should be able to install the 4.0 version: 
http://packages.linuxmint.com/search.php?release=virginia&section=any&keyword=xreader
(You may not need all of those packages - run `dpkg --list | grep xreader` to see the ones you should replace)

If something goes wrong (dependency issue), `apt install -f` should restore everything.

I still recommend upgrading to 21.3 (or 22) if possible.

**Comment by 0xAlMo3geZ** [comment]
Thanks a lot for the response, will do!
