### ISSUE TITLE
'Save Current Settings as Default' does not

### ISSUE THREAD

**Issue by markfilipak** [linuxmint/xreader#67]
'Adjust the zoom level' toolbar drop down defaults to '70%'. Changing it to '100%' and then selecting 'Edit' (menu) > 'Save Current Settings as Default' fails to set the default zoom level to '100%'. On next launch, zoom level is once again '70%'.

**Comment by jhmos** [comment]
I also have this problem with version 1.08 under Linux Mint 18. I have a UHD display and xreader always defaults to a tiny window. Can't see anywhere where preferences are saved.

**Comment by markfilipak** [comment]
My version of xreader is '1.0.8-sarah' (as reported by Synaptic). It has not been updated since I posted, yet something has changed its behavior.

Here's what I did: I launched xreader -- it came up small and with 'Fit Page Width'. Then I loaded a PDF and maximized xreader. Then I changed zoom level to '100%'. Then I used the 'Edit' menu to 'Save Current Settings as Default'. Then I closed xreader.

Then I launched xreader again -- again it came up small, but this time with '100%'! Then I loaded the PDF and xreader maximized (and it retained '100%'). Then I restored xreader back to a floating window (and it retained '100%'). Then I quit xreader.

Then I launched xreader again -- again it came up small, but with '100%'! Then I loaded the PDF and xreader stayed a floating window (and it retained '100%').

It seems that maximizing xreader taught it a 'lesson', and it's behaving normally now.

Try it and report back. Ciao!

**Comment by jhmos** [comment]
I tried reproducing your fix, but it didn't work for me. No configuration file gets changed under my home directory when I 'Save Current Settings as Default' either. Are you using Mate or Cinnamon?

**Comment by markfilipak** [comment]
Mint 18 64-bit, Cinnamon 3.0.7.

**Comment by markfilipak** [comment]
Following one day of fairly normal operation, xreader has resumed it's aberrant behavior. I'm mystified and frustrated.

**Comment by Piiit** [comment]
Save config as default things apply only for newly opened files. Xreader saves for each already opened file the configuration active at that time. That is, the current page and zoom and views... 

Maybe that is the issue here.... Right? Or, did I misunderstand your bug reports?

**Comment by markfilipak** [comment]
Hi Piiit -- how do you pronounce that? 'Piiit'? Hahahahahahaha.......

Okay, an individual 'Save Current Settings as Default' for each document? Is that what you're saying?

...But after using 'Save Current Settings as Default' one time, I'm not changing it. The xreader program is changing it. That's a bug, I think.

**Comment by Piiit** [comment]
@markfilipak It is pronounced as "Pete"... just a german parody :-)

Could you try to open a new document after using 'Save Current Settings as Default', does the bug still show up then?

I tried the following: 
- Open a PDF, set zoom to 70%,  click on 'Save Current Settings as Default'
- Open a new document (never seen before by Xreader), zoom is at 70%
- Open an already seen document which had zoom at 110%, zoom is at 110% (not 70)
- Open a new document again, zoom is at 70%

Do these steps correspond to your steps? Could you please make a step-by-step example on what you do exactly?

**Comment by hub2git** [comment]
I'm on Linux Mint 18.1. xreader is version 1.2.2. "Save current settings" don't work me, too. I click "save current settings" when I have inverted colors. But all future PDFs are still not color-inverted. Does version 1.4.2 fix things?

**Comment by Piiit** [comment]
@hub2git This should be saved with PR #142. However, I am not sure about the other issues mentioned here.

**Comment by hub2git** [comment]
@piiit thank you for letting me know. Finally, this little bug is quashed.

**Comment by hub2git** [comment]
Just wanna confirm that the bug is indeed squashed. 
Using Linux Mint 18.2 Xfce 64-bit.

**Comment by whiskytroll** [comment]
I'm sorry, but I don't understand, isn't "default" some kind of fall back setting? That is - if I haven't already specified anything for this particular document it should revert to default? Isn't it somewhat unintuitive to use that as a per document setting? If I think so, should I post a new report or could I expand my viewpoint here?

**Comment by Piiit** [comment]
@whiskytroll Here "default" means settings for never-seen documents. All other documents remember their last settings (current page number, zoom level, etc.)... It is useful IMO, because all documents can be read and continued reading after some time without setting a bookmark each time. Or zooming in/out again....
But that is just my taste.
It was first introduced to evince (so it is the standard behaviour in all gpdf/evince based viewers)
