### ISSUE TITLE
Buildsystem: `make install` needs `sudo` also if `--exec-prefix` points to a writable destination

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xreader#68]
I get the following error when I try to run 'make install' with xreader
```
/bin/mkdir -p '/usr/share/gir-1.0'
/usr/bin/install -c -m 644 XreaderDocument-1.5.0.gir '/usr/share/gir-1.0'
/usr/bin/install: Deleting '/usr/share/gir-1.0/XreaderDocument-1.5.0.gir' is not possible: No permissions
Makefile:1045: Rule for target „install-girDATA“ failed
```

I translated some parts of it by my self, maybe they are slightly different originaly
(talking about the make output)

I run ./autogen.sh before as follows
```
./autogen.sh                     \
       --prefix=$PWD/install/         \
       --exec-prefix=$PWD/install/ \
       --enable-debug                 \
       --enable-tests                 \
       --enable-caja                 \
       --enable-nemo               \
       --enable-pixbuf             \
       --enable-introspection      \
       --enable-gtk-doc
```

I think it is a bug, that it tries to install something outside $PWD/install. Am I right?
To work around this issue I need to run make install with sudo, which should not be the case to have a second development version running, which does not interfere with the installed packages

**Comment by Piiit** [comment]
Update: With the following disabled options `make install` no longer requires `sudo`.
```
--disable-caja 
--disable-nemo
--disable-introspection
```

**Comment by icarter09** [comment]
@Piiit are you still experiencing this issue?

**Comment by Piiit** [comment]
@icarter09 This issue is deprecated. I close it
