### ISSUE TITLE
pyxreader: thumbnail-frame.png not found

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xreader#72]
After `sudo make install` inside /files/ - folder and executing pyxreader, I get the following error...
I can see the pdf, but no thumbnails within the side pane.

```
(pyxreader:22085): Gtk-WARNING **: 
Error loading image 'file:///usr/share/themes/Mint-Y/gtk-3.0/assets/thumbnail-frame.png': 
No such file or directory
```

**Comment by JosephMcc** [comment]
I added the missing image to Mint-Y in git master. This isn't an issue with xreader.

**Comment by Piiit** [comment]
@JosephMcc I close it then.
