### ISSUE TITLE
Blurred PDF on Hi-DPI display

### ISSUE THREAD

**Issue by jrysig** [linuxmint/xreader#82]
Version 1.2.1 displays blurred PDF on Hi-DPI display.
What is current state of Xreader Hi-DPI support?

![hidpi](https://cloud.githubusercontent.com/assets/7038517/20296117/4c414b76-ab09-11e6-862a-816b285a75ab.png)

**Comment by icarter09** [comment]
@jrysig are you still experiencing this issue?
