### ISSUE TITLE
Huge Annotation window after using 'Accessibility > High Contrast' for a short time 

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xreader#87]
Title and icons are huge

![2 _rdf pdf 2 rdf pptx_039](https://cloud.githubusercontent.com/assets/6096063/20917428/c10e42d6-bb91-11e6-9ece-628361ee6b6d.jpg)

NB: I disabled 'High Contrast' already.

**Comment by JosephMcc** [comment]
For me this has nothing to do with using high contrast. It's like that all the time.

**Comment by JosephMcc** [comment]
Both the icons size and window border color issues should now be fixed.

**Comment by Piiit** [comment]
@JosephMcc Tested, everything working... thx! The high-contrast thing seems to be a coincidence only...
