### ISSUE TITLE
Using CTRL+A to select all text in a form entry does not work

### ISSUE THREAD

**Issue by Nihlus** [linuxmint/xreader#88]
For certain types of PDF forms, CTRL+A does not work for selecting all text in an active form entry. Instead, it will select all text in the entire document.

A PDF exhibiting this behaviour has been attached.
[Character Sheet (3p) - Empty.pdf](https://github.com/linuxmint/xreader/files/644590/Character.Sheet.3p.-.Empty.pdf)

This bug has been seen on the following system configuration:
Xreader 1.0.8
Linux Mint 18, Cinnamon Edition (x64)

**Comment by Piiit** [comment]
I can reproduce this issue on any document with any text-like form field
