### ISSUE TITLE
Clicking in an active PDF form field does not change the cursor position

### ISSUE THREAD

**Issue by Nihlus** [linuxmint/xreader#89]
For certain types of PDF forms, clicking in an active text field will not change the cursor position as expected. Instead, it will unfocus the active field.

A PDF exhibiting this behaviour has been attached.
[Character Sheet (3p) - Empty.pdf](https://github.com/linuxmint/xreader/files/644590/Character.Sheet.3p.-.Empty.pdf)

This bug has been seen on the following system configuration:
Xreader 1.0.8
Linux Mint 18, Cinnamon Edition (x64)

**Comment by Piiit** [comment]
I can reproduce this issue on any document with form fields.

**Comment by icarter09** [comment]
Xreader 2.6.4
Mint 20 64bit

I'm not able to reproduce this issue withe the provided pdf. @Nihlus or @Piiit are either of you still experiencing this issue? Thanks.

**Comment by Nihlus** [comment]
@icarter09 Yeah, I'm still experiencing this with XReader 2.6.4. Try with the large "Features & Traits" field - type some text into it, then try to move the cursor by clicking elsewhere in the text.

**Comment by icarter09** [comment]
@Nihlus thanks for the update. It appears that @Piiit comment is correct. Works as intended with single line edit fields, but multi-line edit fields are displaying the issue.

**Comment by icarter09** [comment]
@Nihlus I just put up a PR that should fix this issue. Thanks.

**Comment by Nihlus** [comment]
Thanks!
