### ISSUE TITLE
Crash when you try to drag page of djvu

### ISSUE THREAD

**Issue by takzhanov** [linuxmint/xreader#92]
Xreader 1.2.2 on Linux Mint 18.1 Serena 64-bit Mate

Try drag page (push down on page area and start drag) using mouse or touchpad - it closes app without any message. Bug reproduced on different djvu files and not on pdf.

/var/log/syslog

```
Jan 19 14:05:27 jorj-Lenovo-B590 kernel: [31508.238527] xreader[23278]: segfault at 1c ip 00007f69797e6c10 sp 00007ffdadecff98 error 4 in libcairo.so.2.11400.6[7f6979779000+10e000]
Jan 19 14:05:27 jorj-Lenovo-B590 org.x.reader.Daemon[1753]: Watch name':1.353' disappeared
Jan 19 14:05:27 jorj-Lenovo-B590 org.x.reader.Daemon[1753]: Watch found URI 'file:///home/jorj/Books/BooksName.djvu' for name; removing
```

**Comment by asyncee** [comment]
I can confirm this bug. It affects me, i experience crashes often, mainly when reading djvu files and trying to interact with it with cursor (when accidently touching the touchpad on my ultrabook).
