### ISSUE TITLE
Some parts of a PDF not shown

### ISSUE THREAD

**Issue by Piiit** [linuxmint/xreader#93]
Open the test file below and see that there is no "Result" text inside the rectangle. 

This works all right in Adobe Reader 8, Foxit Reader and Okular.
![auswahl_055](https://cloud.githubusercontent.com/assets/6096063/22627566/cb9582be-ebc5-11e6-8a50-6b09daedbeb5.jpg)

The error occurs in xreader 1.2.1, atril 1.16.1 and evince 3.18.2...
![auswahl_054](https://cloud.githubusercontent.com/assets/6096063/22627562/b586fd5e-ebc5-11e6-8d21-0681dc371357.jpg)

Test file: [Missing Parts.pdf](https://github.com/linuxmint/xreader/files/753085/Missing.Parts.pdf)

**UPDATE**: Zooming in and out shows the content of the rectangle temporarily...

**Comment by surenenfiajyan** [comment]
Worked normally with 125% , 200% and 300% zoom in Evince.

**Comment by lalincedeldeserto** [comment]
The same happens to me. Some parts of pdf are not visible.  
[output.pdf](https://github.com/linuxmint/xreader/files/2594453/output.pdf) 
![immagine](https://user-images.githubusercontent.com/33136381/48696332-f081af80-ebe1-11e8-886a-95d31f2f66f7.png)

Instead with firefox pdf reader are visible.
![immagine](https://user-images.githubusercontent.com/33136381/48696316-dfd13980-ebe1-11e8-9a0d-9f3d36c4e1a6.png)

**Comment by Piiit** [comment]
Seems to be a poppler issue related to the cairo backend, since it works with Okular on the same version of Poppler.

https://gitlab.freedesktop.org/poppler/poppler/issues/653

**Comment by icarter09** [comment]
@Piiit can this ticket be closed since it's a Poppler issue?
