### ISSUE TITLE
Caja extension build issues

### ISSUE THREAD

**Issue by rezso** [linuxmint/xreader#94]
There are issues with build with/without caja extension:
- caja is required, even if --disable-caja passed:
ev-properties-view.c:31:28: fatal error: glib/gi18n-lib.h: No such file or directory
- caja can use both gtk2/gtk3, but gtk2 is required for caja extension:
PKG_CHECK_MODULES([CAJA],[gtk+-x11-2.0 $MM gthread-2.0 libcaja-extension]

**Comment by Piiit** [comment]
I can confirm this issue

**Comment by Piiit** [comment]
@rezso caja needs gtk2 currently, it is not fully gtk3 ready yet on mint AFAIK. We should nevertheless fix the build, and make it build only if --enable-caja is active during autogen.sh...

**Comment by Piiit** [comment]
@rezso Hi, I created PR #98 ... could you check if that solve your issue?

**Comment by rezso** [comment]
Not.
with --enable-nemo --disable-caja:

make[3]: *** No rule to make target '../properties-nemo/libevproperties.la', needed by 'xreader'. Stop.

In addition, gtk2 is required, but both xreader and nemo uses gtk3.

**Comment by Piiit** [comment]
@rezso Is this fixed now?

**Comment by rezso** [comment]
@Piiit Yes, thank you. I can compile it now with --enable-nemo --disable-caja (caja plugin not needed for me, because atril ships an caja plugin, and both atril and caja are parts of MATE).
