### ISSUE TITLE
after update i lost the feature open pdf files from thunderbird (now opens gimp)

### ISSUE THREAD

**Issue by ferslash** [linuxmint/xreader#99]
I am using cinnamond serena, i update everyday, and after updating i lost a feature:

* the feature i lost was the document reader (xreader) opens pdf automaticly from thunderbird
(after re install the full o.s. and update, bug was still was there, i had to link pdf to xreader manually)

best regards

(this is the very first time that an update brokes my sistem, now i set the update policy to "not broke my sistem) :(

best regards

fer

**Comment by Piiit** [comment]
@ferslash Do you mean that you start Thunderbird and their you get an Email with PDF attached, and opening that opens no longer Xreader, but another application?

**Comment by ferslash** [comment]
yes...


i re-installed the whole linux mint cinamond, again, and after updating all the packeges again, i noticed that a dialog box opened from the lm update manager that was asking me about changing some files related to gnome... it says "do you want to replace the files with the update or keep your existing configuration"


this time i chose "keep" my file (not to replace them) and everything worked just fine...


( so actually it was me who broke linux by chosing "replace files with the updated files"... but maybe we should not allow the update manager to propose to update this gnome files)


i wish i made my self clear (as you can see english is not my first language)


thanks for replaying and i wish this new information can help or just close the tiket since it was kind of my foult :(


best regards from mexico


fer


________________________________
De: Piiit <notifications@github.com>
Enviado: lunes, 20 de marzo de 2017 07:51 a. m.
Para: linuxmint/xreader
Cc: ferslash; Mention
Asunto: Re: [linuxmint/xreader] after update i lost the feature open pdf files from thunderbird (now opens gimp) (#99)


@ferslash<https://github.com/ferslash> Do you mean that you start Thunderbird and their you get an Email with PDF attached, and opening that opens no longer Xreader, but another application?

**Comment by JosephMcc** [comment]
Thanks for updating.
